### ISSUE TITLE
Parallelism

### ISSUE THREAD

**Issue by joeduffy** [pulumi/pulumi#106]
At the moment, all of our DAGs are topologically sorted into a linear ordering.  As a result, we do not exploit inherent parallelism within the dependency graph.  We should fix this.

Note that we will need to be careful about AWS rate-limiting, most likely by limiting the width of the fanout, and also recognizing rate-limiting errors and performing automatic retries.

**Comment by hausdorff** [comment]
Tagging with `kubernetes/inner-dev-loop` because this is **critical** for Pulumi to be a drop-in replacement for `kubectl`.

Lack of parallelism seriously impacts the way app code is written. Where most `kubectl` users are used to being able to blat a bunch of YAML into the cluster and have the system "eventually" converge on working infrastructure (_e.g._, the Deployment fails continually until a PVC is successfully allocated, then the Deployment binds, then it succeeds), in Pulumi, the lack of parallelism requires users to specify the _exact_ dependency constraints for _every API object_.

I believe most users will interpret this as an unreasonable burden when this is comparatively so easy in `kubectl`.

**Comment by swgillespie** [comment]
Based on yesterday's design meeting, I've created three concrete issues that I will pursue in M16:

* [ ] https://github.com/pulumi/pulumi/issues/1623 - Pull out step generation from PlanIterator into its own component
* [ ] https://github.com/pulumi/pulumi/issues/1624 - Execute resource create and update steps and step chains in parallel
* [ ] https://github.com/pulumi/pulumi/issues/1626 - Re-introduce per resource deployment states

I think it is a reasonable goal for M16 to parallelize all steps other than delete steps.

**Comment by swgillespie** [comment]
At this point we're capable of parallelizing all resource operations other than deletes. https://github.com/pulumi/pulumi/issues/1625 tracks parallelizing deletes, and https://github.com/pulumi/pulumi/issues/1758 tracks thinking about how we'd like to fan out work. I'm going to close out this issue and track the remaining tasks in these follow-up issues.
