### ISSUE TITLE
Tracking Issue: Splitting Types in NodeJS

### ISSUE THREAD

**Issue by RobbieMcKinstry** [pulumi/pulumi#11558]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

This issue tracks multiple issues related to splitting files in the `/types` directory into smaller units. Originally, this work was completed in https://github.com/pulumi/pulumi/pull/10831 but reverted in https://github.com/pulumi/pulumi/pull/11534 due to [a bug in TSC](https://github.com/Microsoft/TypeScript/issues/25677). The issues below are listed in priority order.

- [x] **Blocker:** https://github.com/pulumi/pulumi/issues/11557
- [ ] **Blocker:** https://github.com/pulumi/pulumi/issues/11560
- [ ] **Optimization:** https://github.com/pulumi/pulumi/issues/11561
- [ ] **Potential Blocker:** https://github.com/pulumi/pulumi/issues/11565
- [ ] **Clean Up:** Close https://github.com/pulumi/pulumi/issues/8613
- [ ]  **Optimization:** https://github.com/pulumi/pulumi/issues/10442

### Affected area/feature

NodeJS code gen

### Related Issues

* https://github.com/pulumi/pulumi/issues/11504
* https://github.com/pulumi/pulumi-azure-native/issues/2108
* https://github.com/pulumi/pulumi-azure-native/issues/1358
* https://github.com/pulumi/pulumi/issues/11531

**Comment by Navigatron** [comment]
A big +1 for this. Using the azure-native provider and creating just three resources, we're seeing:

```
[xxx]$ NODE_OPTIONS=--max-old-space-size=6000 tsc --extendedDiagnostics
Files:                        30888
Lines of Library:             29152
Lines of Definitions:       5098802
Lines of TypeScript:            240
Lines of JavaScript:              0
Lines of JSON:                    0
Lines of Other:                   0
Identifiers:                4024654
Symbols:                    1974508
Types:                           88
Instantiations:                   0
Memory used:               3475317K
Assignability cache size:         0
Identity cache size:              0
Subtype cache size:               0
Strict subtype cache size:        0
I/O Read time:               15.91s
Parse time:                  27.31s
ResolveModule time:           5.52s
ResolveTypeReference time:    0.09s
Program time:                56.65s
Bind time:                   72.25s
Total time:                 128.90s
```
Also related:
- https://github.com/pulumi/pulumi-azure-native/issues/1997
- https://github.com/pulumi/pulumi-azure-native/issues/932
