### ISSUE TITLE
[Epic] Amazing Performance Initiative

### ISSUE THREAD

**Issue by RobbieMcKinstry** [pulumi/pulumi#11598]
## Overview

"Amazing Performance" is an Platform Team initiative that started in Q3 2022 and continued in Q4 2022. The objective is to improve performance (primarily runtime but, to a less degree, memory consumption) for as many users as possible.

## Backlog

- [ ] https://github.com/pulumi/pulumi/issues/12547 https://github.com/pulumi/pulumi/labels/help-wanted https://github.com/pulumi/pulumi/labels/good-first-issue
- [ ] https://github.com/pulumi/pulumi/issues/10442
- [ ] https://github.com/pulumi/pulumi/issues/10210
- [ ] https://github.com/pulumi/pulumi/issues/10403
- [ ] https://github.com/pulumi/pulumi/pull/10122
- [ ] https://github.com/pulumi/pulumi/issues/10403
- [ ] https://github.com/pulumi/pulumi/issues/2928 
- [ ] https://github.com/pulumi/pulumi/issues/10607
- [ ] https://github.com/pulumi/pulumi/issues/10010
- [ ] https://github.com/pulumi/pulumi/issues/7311  https://github.com/pulumi/pulumi/labels/help-wanted
- [ ] https://github.com/pulumi/pulumi/issues/7146
- [x] https://github.com/pulumi/pulumi/issues/4876
- [ ] https://github.com/pulumi/pulumi/issues/10403
- [ ] Increase usage of Go build caching by adding it into `templates` https://github.com/pulumi/pulumi/labels/help-wanted
- [x] https://github.com/pulumi/pulumi/issues/12351
- [ ] Ensure plugin downloads and TypeScript compilation have spans in the trace

##  Out of scope

Related work items and ideas for the future, likely out scope but retained here in case they need to be pulled in:

### Tracing improvements

- [ ] Upgrade from opentracing to opentelemetry https://github.com/pulumi/pulumi/labels/help-wanted
- [x] https://github.com/pulumi/pulumi/issues/7148
- [ ] https://github.com/pulumi/pulumi/issues/3671
   - [x] Mitigate Service call overhead in httpstate backend 
   - [ ] Improve language runtime init 
     - [x] #2201
     - [ ] Mitigate TS compilation (on larger projects runs into 10s of seconds eg see https://github.com/pulumi/pulumi/pull/9049#issuecomment-1051237488)
        - [ ] Allow opt-in for faster SWC https://github.com/pulumi/pulumi/pull/9049 
        - [ ] Allow user upgrades of TypeScript+ts-node https://github.com/pulumi/pulumi/pull/10122
   - [ ] Prewarm providers when imported
- [x] *Related* see performance section of azure-native 2.0 epic https://github.com/pulumi/home/issues/2061
   - [ ]  https://github.com/pulumi/pulumi-azure-native/issues/932

### Misc

- [ ] https://github.com/pulumi/pulumi/issues/10487

### Benchmarks and metrics improvements

- [ ] Add a CI status check to ensure PRs don't violate performance SLAs (proactively enforce SLAs instead of reactively enforcing them)
- [ ] Add a metric for Service client network bandwidth
- [ ] Add a benchmark to measure Secret handling
- [x] Collect data on using service vs local backend

## M82

- [x] https://github.com/pulumi/pulumi/pull/11481
- [ ] https://github.com/pulumi/pulumi/issues/8613
- [ ] https://github.com/pulumi/pulumi/issues/10442

## M80

- [x] ~~https://github.com/pulumi/pulumi/issues/8613~~ (Reverted, see https://github.com/pulumi/pulumi/issues/11558)

## M79

- [x] https://github.com/pulumi/pulumi/issues/11116

### M78
- [x] https://github.com/pulumi/pulumi/pull/10636
- [x] https://github.com/pulumi/pulumi/pull/10661
- [x] https://github.com/pulumi/pulumi/issues/10180
- [x] https://github.com/pulumi/home/issues/2294
- [x] https://github.com/pulumi/templates/pull/362
- [x] https://github.com/pulumi/pulumi/pull/10770
- [x] https://github.com/pulumi/pulumi-trace-tool/pull/3
- [x] https://github.com/pulumi/pulumi/issues/10473
- [x] https://github.com/pulumi/pulumi/pull/10830
- [x] https://github.com/pulumi/pulumi/pull/10828
- [x] Recalibrate performance benchmark alerting thresholds after recent measurement fixes
- [x]  Build a cost model for basic programs that use one cloud provider 
- [x]  Build a client for the new efficient PATCH checkpoint protocol
- [x] *Support Service team* https://github.com/pulumi/pulumi-service/issues/6497
   - [ ] *Related* https://github.com/pulumi/home/issues/1768

### M77
- [x] https://github.com/pulumi/home/issues/2229
- [x] https://github.com/pulumi/pulumi/issues/10350
- [x] https://github.com/pulumi/home/issues/1498
- [x] https://github.com/pulumi/home/issues/2200
- [x] https://github.com/pulumi/pulumi/issues/7653
- [x] https://github.com/pulumi/examples/pull/1271
- [x] https://github.com/pulumi/home/issues/2129

### M75

- [x] https://github.com/pulumi/pulumi/pull/10173 
- [x] https://github.com/pulumi/pulumi/issues/7571
- [x] https://github.com/pulumi/pulumi/pull/10037
- [x] "Importing "typescript" is costing 300ms startup even when unused": https://github.com/pulumi/pulumi/pull/10185 && https://github.com/pulumi/pulumi/pull/10214
- [x] https://github.com/pulumi/templates/pull/312

**Comment by brandonkal** [comment]
Was this stalled?
