### ISSUE TITLE
[Epic] Output helpers

### ISSUE THREAD

**Issue by justinvp** [pulumi/pulumi#11939]
## Overview

Cover 90% of `Output.Apply` usage with custom Output methods like `jsonStringify` and update all examples and other usage to use them.

### References 📔

Based on Luke's hackathon project:

- https://github.com/pulumi/pulumi/compare/lukehoban/outputhelpers
- https://github.com/pulumi/examples/compare/lukehoban/outputhelpers
- [x] PR/FAQ
- [x] https://github.com/pulumi/pulumi/issues/12174

#### `jsonStringify`/`jsonParse`

Tracked in https://github.com/pulumi/pulumi/issues/12519.

#### `toString`

- [ ] #12143
- [ ] Python
- [ ] .NET
- [ ] Go
- [ ] Java?

#### `arrayConcat`

- [ ] Node.js
- [ ] Python
- [ ] .NET
- [ ] Go
- [ ] Java?

#### `stringSplit`

- [ ] Node.js
- [ ] Python
- [ ] .NET
- [ ] Go
- [ ] Java?

#### `nullCoalesce`

- [ ] Node.js
- [ ] Python
- [ ] .NET
- [ ] Go
- [ ] Java?

#### programgen

- [ ] Node.js
- [ ] Python
- [ ] .NET
- [ ] Go
- [ ] Java?

#### Update usage

- [ ] Add to docs
- [ ] Update all examples
- [ ] Update arch templates
- [ ] Update internal codebases

**Comment by Frassle** [comment]
`stringSplit` can probably be done via an std call, no need to be an intrinsic.

**Comment by justinvp** [comment]
> `stringSplit` can probably be done via an std call, no need to be an intrinsic

While this could be done via a std call, the aim for these are to simplify the programming model and we'd like to have all the mainline helpers in the same place for discoverability.
