### ISSUE TITLE
[Epic] Project-scoped stacks in the filestate backend

### ISSUE THREAD

**Issue by justinvp** [pulumi/pulumi#12173]
## Overview

Add support for project-scoped stacks in the filestate backend for consistency with the httpstate backend.

### Work Items ⚙️

- [x] Design doc ([summary](https://github.com/pulumi/pulumi/issues/2522#issuecomment-1426496284))
- [x] https://github.com/pulumi/pulumi/issues/2522
- [x] Docs: https://github.com/pulumi/pulumi-hugo/pull/2465
- [x] Blog: https://github.com/pulumi/pulumi-hugo/pull/2622

**Comment by abhinav** [comment]
Feature released in v3.61.0.
Blog post published: https://www.pulumi.com/blog/project-scoped-stacks-in-self-managed-backend/
Documentation updated: https://www.pulumi.com/docs/intro/concepts/state/#scoping

Closing as done.

**Comment by catmeme** [comment]
The design doc and blog post mention something that the documentation does not.

> All projects in a self-managed backend are placed under a virtual organization named “organization”. This value is constant and cannot be changed.

This use of literal `organization` creates friction moving states between the Pulumi Cloud and filestate backends because fully qualified stack names are different.

Is the intention is to use partially qualified references to ease that friction? e.g. `project/stack`?

**Comment by Frassle** [comment]
> Stacks cannot be referenced as my-project/my-stack.

This is an oddity with the cloud backend as well. When qualification was first needed it was far more common to need to specify the organisation, not the project and so X/Y was introduced to allow that. It does mean there's no good way to map over project references between the backends now though.

This did come up during the design phase for this work, but given the constraints around backwards compatibility for existing partial references there didn't look to be anything we could improve.

Seeing this use case though I wonder if it would have been enough to be able to just set what fixed string the filestate used for the orgnaization name, that is rather than it being fixed to "organization" you could have set it to "my-org". Would that have covered your uses?

**Comment by Frassle** [comment]
Raised it as an issue https://github.com/pulumi/pulumi/issues/13980 to track at the least.
