### ISSUE TITLE
[Epic] JSON Helpers

### ISSUE THREAD

**Issue by lukehoban** [pulumi/pulumi#12519]
## Overview

JSON stringify and parse over Pulumi Output values are two of the most common operations that trip up users and make common code patterns more complicated than they need to be.

We will add customer JSON APIs that work natively with Outputs o each of the Pulumi language SDKS.

This is a first step in a boarder investment in "Output Helpers" for a wider variety of scenarios - tracked in https://github.com/pulumi/pulumi/issues/11939.

### References 📔

Based on Luke's hackathon project:

- https://github.com/pulumi/pulumi/compare/lukehoban/outputhelpers
- https://github.com/pulumi/examples/compare/lukehoban/outputhelpers
- [x] [PR/FAQ](https://docs.google.com/document/d/13v0e8G9ieEsr4Qj6m1S_BJ_X07W7yEjep-WP9THe_h4/edit)

#### `jsonStringify`

- [x] https://github.com/pulumi/pulumi/pull/11605
- [x] https://github.com/pulumi/examples/pull/1332
- [x] https://github.com/pulumi/pulumi/pull/11607
- [x] https://github.com/pulumi/examples/pull/1331
- [x] https://github.com/pulumi/pulumi/pull/11556
- [x] https://github.com/pulumi/pulumi/pull/11609
- [x] https://github.com/pulumi/pulumi-hugo/issues/2556
- [ ] https://github.com/pulumi/examples/pull/1325

#### `jsonParse`

- [x] https://github.com/pulumi/pulumi/pull/11735
- [x] https://github.com/pulumi/pulumi/pull/11741
- [x] https://github.com/pulumi/pulumi-dotnet/pull/65
- [x] https://github.com/pulumi/pulumi/pull/11745
- [x] https://github.com/pulumi/pulumi-hugo/issues/2556
- [ ] Update examples

#### `jsonStringify`

- [ ] Java?
- [ ] Update Java examples?

#### `jsonParse`

- [ ] Java?
- [ ] Update Java examples?

**Comment by justinvp** [comment]
We need a blog post, but otherwise this is complete. There is some follow-up work to update a couple examples and improve Go: https://github.com/pulumi/pulumi/issues/12460
