### ISSUE TITLE
[Epic] Matrix Testing

### ISSUE THREAD

**Issue by justinvp** [pulumi/pulumi#12686]
This epic tracks making a new test system that's more general than ProgramTest that can be used to give coverage of the runtimes and sdkgen/programgen.

- Code generation and project setup/install needs to be on the language plugin interface so we can call that dynamically
- The tests need to be written in PCL and schemas so that we can dynamically run and test programgen and sdkgen
- The tests need to be written once in `pulumi/pulumi` in a way that other language repos can pull in and use

## Test Sets

We'll need to write a new set of tests that exercise the language runtimes and codegen:

### L0

This is the simplest test set, the intention is pretty much to just check that we can handle “types”, “inputs” (i.e. config), and “outputs” (i.e. stack outputs).
We’ll probably want to test some very basic builtin functions at this layer, mostly around making sure stack outputs are correct (i.e. we need secret/unsecret builtins). But I don’t expect this test set to cover things like non-construction expressions (we need construction expressions like `[1, 2, 3]`) or non-trivial builtins (e.g. concat, tojson, etc).
This would also test that StackReferences work as those are a core feature of the runtime SDK and don’t depend on sdkgen.

### L1 (Provider-level Tests)

This adds in providers and sdkgen. Again we’ll be keeping expressions simple (limited to the set above), but we’ll check that we can sdkgen for various schemas and ensure the runtime behavior of them (e.g. input fields marked secret should go to the engine secret even if the value passed in isn’t). We’d also test resource options in this test set.

### L2 (Program-level engine tests)

This is intended to cover everything we expect for a sensible minimal pulumi implementation (e.g. think yaml v1). This will cover expressions and builtins that we think are highly critical to general usage.

### L3 (Program-level SDK tests)

This covers everything else. Any expressions or builtins not covered above would have tests added in here, as well as things like components and support for `apply`.

## Work Items

- [x] Planning doc [Fraser]: https://docs.google.com/document/d/1ZUfspwN4ddaoy5aORXvgq4VrhM6nbDUeVvWP20wS0k8/edit#heading=h.fldxp4bqhf7e
- [x] [Add codegen gRPCs to language service](https://github.com/pulumi/pulumi/pull/11224)
- [ ] Add gRPC engine service for retrieving and running tests
- [x] Add a couple basic L0 tests
- [ ] Add codegen support in language plugin
    - [ ] Node.js
    - [ ] Go
    - [ ] Python
    - [ ] .NET
    - [ ] Java
    - [ ] YAML
- [ ] Retrieve and run tests for each language
    - [ ] Node.js
    - [ ] Go
    - [ ] Python
    - [ ] .NET
    - [ ] Java
    - [ ] YAML
- [ ] Flesh out L0 tests
- [ ] Add L1 tests
- [ ] Add L2 tests
- [ ] Add L3 tests

**Comment by Frassle** [comment]
Conformance tests are now a thing and running in each repo. We will keep adding more and moving codegen tests to conformance tests as we go.
