### ISSUE TITLE
[Epic] Support User-Selected TypeScript Versions

### ISSUE THREAD

**Issue by justinvp** [pulumi/pulumi#12687]
This epic extends https://github.com/pulumi/pulumi/issues/12117 to support user-selected versions of TypeScript.
For backwards compatibility we must maintain support for the TypeScript v3 line. However, with the release of TypeScript v5 we would like to allow users the option to upgrade.

This epic will allow users to select the version of TypeScript they want to use, allowing us to support the v3, v4, and v5 lines.

#4876 is tightly related to this issue because TS-Node has variable support for TypeScript. Certain versions of TS-Node only support certain versions of TypeScript. Thus, getting us to the latest compatible version of TS-Node is a prerequisite for supporting user-selected versions of TypeScript.

Next, we intend to allow users to select their version of TypeScript using peer dependencies (https://github.com/pulumi/pulumi/pull/10122). Marking TypeScript and TS-Node as peer-dependencies is _technically_ a breaking change, but we will employ various mitigation strategies to minimize the impact. To ensure we don't break for user's on older versions of npm or yarn classic, we vendor ts 3.8.3 and ts-node 7.0.1 and fallback to these versions if no peer-dependencies are present.

Function serialisation uses typescript/lib, and we need to update our usage here to work around incompatible changes, as well as making the test suite cope with slightly different output depending the used version of typescript.

# Intermediate Steps

```[tasklist]
- [ ] https://github.com/pulumi/pulumi/issues/12936
- [ ] https://github.com/pulumi/pulumi/issues/12965
- [ ] https://github.com/pulumi/pulumi/issues/12966
- [ ] https://github.com/pulumi/pulumi/issues/15733
- [ ] https://github.com/pulumi/pulumi/issues/15734
- [ ] https://github.com/pulumi/pulumi/issues/15735
- [ ] https://github.com/pulumi/pulumi/issues/4876
- [ ] https://github.com/pulumi/templates/issues/583
- [ ] Add TypeScript as dependency to examples
- [x] Add documentation for TypeScript versions https://github.com/pulumi/pulumi-hugo/pull/4161
```
