### ISSUE TITLE
[Epic] Python: Improved Typing

### ISSUE THREAD

**Issue by justinvp** [pulumi/pulumi#12689]
For Python codegen we generate classes for inputs of object type to enable strong typing for these inputs. However, this leads to somewhat verbose syntax, requiring to instantiate the "args classes". See https://github.com/pulumi/pulumi/discussions/11500 for a motivating example.

With [PEP 589 – TypedDict](https://peps.python.org/pep-0589/) and [PEP 655 – Marking individual TypedDict items as required or potentially-missing](https://peps.python.org/pep-0655/) there is now a more concise way to achieve the same result.

For each input object type we can generate a <Type>Args class as before, as well as a <Type>ArgsDict TypedDict based type. To support backwards compatibility, inputs of object type will accept the union of the two types.

```python
class MyTypeArgsDict(TypedDict):
    my_prop: pulumi.Input[str]
    my_other_prop: NotRequired[pulumi.Input[float]]
```

Related issues: https://github.com/pulumi/pulumi/issues/11732

### Example with <Type>Args

```python
from pulumi_kubernetes.apps.v1 import Deployment
from pulumi_kubernetes.apps.v1 import Deployment, DeploymentSpecArgs
from pulumi_kubernetes.meta.v1 import LabelSelectorArgs, ObjectMetaArgs
from pulumi_kubernetes.core.v1 import ContainerArgs, PodSpecArgs, PodTemplateSpecArgs

app_labels = {"app": "nginx"}
deployment = Deployment(
    "nginx",
    spec=DeploymentSpecArgs(
        selector=LabelSelectorArgs(match_labels=app_labels),
        replicas=1,
        template=PodTemplateSpecArgs(
            metadata=ObjectMetaArgs(labels=app_labels),
            spec=PodSpecArgs(containers=[ContainerArgs(name="nginx", image="nginx")]),
        ),
    ),
)
```

### Example with <Type>ArgsDict

```python
from pulumi_kubernetes.apps.v1 import Deployment

app_labels = {"app": "nginx"}

deployment = Deployment(
    "nginx",
    spec={
        "selector": {"match_labels": app_labels},
        "replicas": 1,
        "template": {
            "metadata": {"labels": app_labels},
            "spec": {"containers": [{"name": "nginx", "image": "nginx"}]},
        },
    },
)
```

## Design (M103)

- [x] Design doc https://docs.google.com/document/d/1qNBzw-W1e80xhVpwQHNbwZ3hlfhMSBX-6TYF6UNcx0c/edit#heading=h.ojtxje7btj58
- Public copy https://docs.google.com/document/d/1fr1qAUE41mQq_YOmrP_aMncfFQXxU85jMpuOTeN9bYo/edit#heading=h.ojtxje7btj58

### M104

- [x] Get started on implementation
- [x] Verify mypy/pyright/pycharm performance for TypedDict
- [x] Review typing error messages for TypedDict

### M106

- [x] https://github.com/pulumi/pulumi/pull/15957
- [x] https://github.com/pulumi/docs/pull/12110
- [x] https://github.com/pulumi/docs/pull/12160

### M107

- [ ] https://github.com/pulumi/pulumi/pull/14871
- [ ] Update registry docs - [discussion doc](Docs discussion https://docs.google.com/document/d/1BT4ILg-q-q-XgYRuDOBOYHdNIiICWcgpewMOhMdFcjE/edit#heading=h.ojtxje7btj58)
- [ ] Verify that generated docs use the new TypedDict types
- [ ] https://github.com/pulumi/pulumi.ai/issues/1011

### Future Iteration
- [ ] https://github.com/pulumi/pulumi/issues/16375
- [ ] https://github.com/pulumi/pulumi/issues/14088

## Rollout & Announce

- [ ] Rollout to tier 1 providers
  - [x] https://github.com/pulumi/pulumi-terraform-bridge/pull/2115
  - [x] https://github.com/pulumi/pulumi-kubernetes/pull/3070
  - [x] https://github.com/pulumi/pulumi-aws/pull/4108
  - [x] https://github.com/pulumi/pulumi-gcp/pull/2116
  - [x] https://github.com/pulumi/pulumi-azure-native/pull/3400
  - [x] https://github.com/pulumi/pulumi-azure/pull/2164
  - [x] https://github.com/pulumi/pulumi-azuredevops/pull/439
  - [x] https://github.com/pulumi/pulumi-azuread/pull/1180
- [ ] Update hand-written documentation examples to use the new TypedDict types
- [ ] Update templates to use new TypedDict types
- [x] Blog post https://github.com/pulumi/docs/pull/12123
- [ ] :icecream:

**Comment by jf** [comment]
hi Justin, for folks interested in the progress of this, where would we go to observe the progress and/or help with things?

**Comment by julienp** [comment]
We have a working implementation in https://github.com/pulumi/pulumi/pull/15957, however we ran into some performance issues when using MyPy [^1].

To work around this, we currently generate the TypedDict based args to behave differently depending on the used type checker. MyPy supports a special variable `MYPY` that is always considered true, and we can use this to hide the TypedDict types from it, and use `Mapping[str, Any]` instead. The PyDantic library currently uses a similar workaround, although for a different performance issue [^2].

Here's an example from the AWS provider:

```python
if not MYPY:
    class InstanceCpuOptionsArgsDict(TypedDict):
        amd_sev_snp: NotRequired[pulumi.Input[str]]
        core_count: NotRequired[pulumi.Input[int]]
        threads_per_core: NotRequired[pulumi.Input[int]]
elif False:
    InstanceCpuOptionsArgsDict: TypeAlias = Mapping[str, Any]
```

When using Pyright, you get the full type checking experience within dictionary arguments, but not with MyPy.

The MyPy behaviour matches the previous implementation where these input types could either take an `Args` class or a `Mapping[str, Any]`. This means that we technically don't have a regression here, and when using Pyright you get a better experience.

However the question then becomes what style of arguments should we encourage? Currently we encourage the `Args` style classes over passing in dictionaries. It is the default for generated code and in documentation. This is not the most pythonic approach and fairly verbose [^3], but does give strong typing and better IDE discoverability.

[^1]: https://github.com/python/mypy/issues/17231
[^2]: https://github.com/pydantic/pydantic-core/pull/528
[^3]: https://github.com/pulumi/pulumi/discussions/11500

**Comment by julienp** [comment]
It looks like PyCharm also picks `Mapping[str, Any]` when confronted with the `if not MYPY/elif False` workaround.

**Comment by justinvp** [comment]
Closing this out as fixed! 🎉 

Blog announcement here: https://www.pulumi.com/blog/pulumi-loves-python/

There is some remaining work to rollout fully across the long tail of providers, docs, and examples, but we'll track the remaining work via the individual issues.
