### ISSUE TITLE
[Epic] Monorepo Support

### ISSUE THREAD

**Issue by justinvp** [pulumi/pulumi#12688]
To better support monorepo patterns, we're aiming to add support for yarn/npm workspaces, which are used by many monorepo tools to manage nodejs dependencies.

This will enable a simpler setup when using monorepo tools like Nx, avoiding using any symlinking/nohoist workarounds.

```[tasklist]
- [ ] https://github.com/pulumi/pulumi/issues/15435
- [ ] https://github.com/pulumi/pulumi/issues/15436
- [ ] https://github.com/pulumi/pulumi/issues/15455
- [ ] https://github.com/pulumi/pulumi/issues/9129
- [ ] https://github.com/pulumi/examples/issues/1605
- [ ] https://github.com/pulumi/pulumi/issues/15512
- [ ] computeCodePaths for pnpm workspaces
```

**Comment by joeduffy** [comment]
Naive question, @justinvp how does this relate to https://github.com/pulumi/pulumi/issues/8865 (and various other monorepro related issues)? Did we just not corral all of them into one place yet? Or are there layers of support here?

**Comment by julienp** [comment]
https://github.com/pulumi/pulumi/issues/8865 is essentially fixed, but I was waiting for the blog post we have about this to go out this week to close it out, so I'd have something more concrete to point people to.
