### ISSUE TITLE
[Epic] Transformations for packaged components

### ISSUE THREAD

**Issue by justinvp** [pulumi/pulumi#12996]
Epic tracking addressing https://github.com/pulumi/pulumi/issues/6948

## Previous Work

- [x] [Original design doc](https://docs.google.com/document/d/13iL6eqpgAmD53gK1j_uUWG61LK_uIpUYcVpQGtyZ624/edit#)
- [x] Hackathon spike

## M95

- [x] [Design doc](https://docs.google.com/document/d/1Jy8xzSnVQ83Vp54vI0Gs0nZP1qm6ZTcoecLWGHJ110g/edit?usp=sharing)
- [x] Design review

## M96

- [x] Get started on Engine and Node SDK

## M101

Ship experimental support in the engine and SDKs:

- [x] https://github.com/pulumi/pulumi/pull/15290
- [x] https://github.com/pulumi/pulumi/pull/15355
- [x] https://github.com/pulumi/pulumi/pull/15376
- [x] [Node SDK](https://github.com/pulumi/pulumi/pull/14303)
- [x] .NET SDK

## M102

- [x] Correctly track dependencies in the engine after transforms are called
- [x] Solicit customer feedback (due 4/12)

## M103

Address feedback

- [x] https://github.com/pulumi/pulumi/issues/15984
- [x] https://github.com/pulumi/pulumi/issues/15973
- [x] https://github.com/pulumi/pulumi/issues/15972

## M106

Announce

- [x] https://github.com/pulumi/pulumi/pull/16080 (shipped in v3.115.0)
- [x] https://github.com/pulumi/docs/pull/11851
- [x] https://github.com/pulumi/docs/pull/11852

## Future

- [ ] Add warning when using old transformations APIs with MLCs (advertise new API)
- [ ] Java SDK
- [ ] Deprecate old transformations APIs
