### ISSUE TITLE
[Epic] Matrix Testing Core Framework

### ISSUE THREAD

**Issue by justinvp** [pulumi/pulumi#13499]
We have a prototype of the matrix testing framework with some trivial programs for Go and Node.js. We need to finish this with support for the other languages so we can start leveraging it in earnest. This epic tracks the minimal amount we need to do to be able to start leveraging this approach for programgen tests.

## M92

- [x] [Planning doc](https://docs.google.com/document/d/1ZUfspwN4ddaoy5aORXvgq4VrhM6nbDUeVvWP20wS0k8/edit#heading=h.fldxp4bqhf7e)
- [x] Test the tests (or just ensure each test is using multiple languages)
- [x] Add ability to specify schemas and pump those through package gen, producing a "linkable" artifact that can be passed to programgen to use. This will require new commands on the language interface. (N.B. This is probably the largest amount of work, but it doubles in that providers also want this for their testing, and it feeds into cleaning up their sdk release processes as well)
- [x] Support snapshot testing of the code (not for correctness, but this is the best way to check code style)
- [x] Ensure that matrix testing is testing the marshalling/unmarshalling of schemas
- [x] [Add codegen capability to Python langhost](https://github.com/pulumi/pulumi/issues/13826)

## Future

- [ ] [Add codegen capability to .NET langhost](https://github.com/pulumi/pulumi-dotnet/issues/176)
- [ ] Write a lot of tests
- [ ] Ensure each language is running matrix tests ([dotnet](https://github.com/pulumi/pulumi-dotnet/issues/177), [python](https://github.com/pulumi/pulumi/issues/13837), [go](https://github.com/pulumi/pulumi/issues/13836))
- [ ] Cleanup old ProgramTests that can be covered by matrix testing
- [ ] Add codegen capability to YAML langhost
- [ ] Add codegen capability to Java langhost

**Comment by justinvp** [comment]
Closing this since https://github.com/pulumi/pulumi/pull/13705 has merged. The main remaining future tasks are tracked as their own follow-up issues.
