### ISSUE TITLE
[Epic] Codegen quality

### ISSUE THREAD

**Issue by justinvp** [pulumi/pulumi#13503]
This is primarily focused on programgen quality. Once https://github.com/pulumi/pulumi/issues/13499 is ready, we'll be leveraging the Matrix Testing Framework as we add tests as part of fixing programgen issues. We'll also be addressing some sdkgen bugs, as well a sdk and engine bugs that new matrix tests uncover.

### M92

- [x] https://github.com/pulumi/pulumi/issues/12986
- [x] https://github.com/pulumi/pulumi/issues/12695
- [x] https://github.com/pulumi/pulumi/issues/13613
- [x] https://github.com/pulumi/pulumi/issues/13151
- [x] https://github.com/pulumi/pulumi/issues/10985
- [x] https://github.com/pulumi/pulumi/issues/13569
- [x] https://github.com/pulumi/pulumi/issues/6469
- [x] https://github.com/pulumi/pulumi/issues/12009
- [x] https://github.com/pulumi/pulumi/issues/8107
- [x] https://github.com/pulumi/pulumi/issues/12507
- [x] https://github.com/pulumi/pulumi-dotnet/issues/21

### M93 - M97
- [x] https://github.com/pulumi/pulumi/issues/14554
- [x] https://github.com/pulumi/pulumi/issues/14734
- [x] https://github.com/pulumi/pulumi/issues/14662
- [x] https://github.com/pulumi/pulumi/issues/14231
- [x] https://github.com/pulumi/pulumi-java/issues/1232
- [x] https://github.com/pulumi/pulumi/issues/14064
- [x] https://github.com/pulumi/pulumi/issues/14037
- [x] https://github.com/pulumi/pulumi/issues/13998
- [x] https://github.com/pulumi/pulumi/issues/13758
- [x] https://github.com/pulumi/pulumi/issues/13751
- [x] https://github.com/pulumi/pulumi/issues/13613
- [x] https://github.com/pulumi/pulumi/issues/13513
- [x] https://github.com/pulumi/pulumi/issues/13498
- [x] https://github.com/pulumi/pulumi/issues/13200
- [x] https://github.com/pulumi/pulumi/issues/13318
- [x] https://github.com/pulumi/pulumi-terraform-bridge/issues/1203
- [x] https://github.com/pulumi/pulumi/issues/13108
- [x] https://github.com/pulumi/pulumi/issues/14483
- [x] https://github.com/pulumi/pulumi/issues/12449

### M98

- [x] Increase code coverage for Go codegen to 90%

### Future

- [ ] https://github.com/pulumi/pulumi/issues/12606
- [ ] https://github.com/pulumi/pulumi/issues/5169
- [ ] https://github.com/pulumi/pulumi/issues/13570
- [x] https://github.com/pulumi/pulumi/issues/12980
- [ ] https://github.com/pulumi/pulumi/issues/11046
- [ ] https://github.com/pulumi/pulumi/issues/13623
- [ ] https://github.com/pulumi/pulumi/issues/13624
- [ ] https://github.com/pulumi/pulumi/issues/13625
- [ ] https://github.com/pulumi/pulumi/issues/7735
- [ ] https://github.com/pulumi/pulumi/issues/13635
- [ ] Following added by @dixler
- [ ] https://github.com/pulumi/pulumi-yaml/issues/480
- [ ] https://github.com/pulumi/pulumi-yaml/issues/479
- [ ] https://github.com/pulumi/pulumi-yaml/issues/478
- [ ] https://github.com/pulumi/pulumi-yaml/issues/477

**Comment by justinvp** [comment]
We've made a bunch of progress here, so closing this as done. Of course, there's always more improvements to be made, and those will be tracked in new epics.
