### ISSUE TITLE
[Epic] CLI Checkpoint Performance

### ISSUE THREAD

**Issue by justinvp** [pulumi/pulumi#13502]
We either want to document and blog about `PULUMI_SKIP_CHECKPOINTS`, possibly promoting it to a CLI flag (or `Pulumi.yaml` option), and consider making it the default behavior with a flag to opt-in to more reliability. As part of this, consider making `PULUMI_SKIP_CHECKPOINTS` batch updates, sending the checkpoint after a certain number of seconds. Ensure it works properly with CTRL+C CTRL+C interrupts better.

We need to put together a decision doc, laying out the options and a proposal. Some options:
- Document the current envvar and write a blog post on it, so it's a documented thing that we can refer people to. Don't make it the default.
- Make it the default. Have a way to opt-in to the old behavior. Document and blog about it.
- Implement some new thing, that's not either extreme. Not every checkpoint saved and not just the first and last.
    - Options that are very low cost
    - Checkpointing every N seconds (e.g. 5 seconds or something like that).
- Journaling
- Any other options that are in between. 

Current implementation:

https://github.com/pulumi/pulumi/blob/5f6832ee8a5cb19afcbd82b6aac8473e3743ea71/pkg/backend/snapshot.go#L744-L750

https://github.com/pulumi/pulumi/blob/5f6832ee8a5cb19afcbd82b6aac8473e3743ea71/pkg/backend/snapshot.go#L672-L702

https://github.com/pulumi/pulumi/blob/5f6832ee8a5cb19afcbd82b6aac8473e3743ea71/pkg/backend/snapshot.go#L704-L718

## Work Items

Remaining issues:

- [x] https://github.com/pulumi/pulumi-service/issues/34341
- [ ] https://github.com/pulumi/home/issues/4404
- [x] https://github.com/pulumi/pulumi-service/issues/34802
- [ ] https://github.com/pulumi/pulumi-service/issues/34813
- [ ] https://github.com/pulumi/pulumi/issues/21182
- [ ] https://github.com/pulumi/pulumi/issues/21190

**Comment by mortaelth** [comment]
the amount of traffic without the PULUMI_SKIP_CHECKPOINTS is just huge. However current implementation of the skipping is the other extreme and we are afraid to use it except some testing stacks which get destroyed anyhow. Having something between like mentioned 5s or 10s sync with storage would convince us to turn it on everywhere.

**Comment by tgummerer** [comment]
Timeline of the next steps here:
- merge the CLI changes https://github.com/pulumi/pulumi/pull/19862 (hopefully this week, should be in next weeks release 2025-09-10)
- finish the server side changes. Hopefully we can get this done by the end of next week 2025-09-17
- turn on the feature flag for pulumi owned orgs, to get internal dogfooding 2025-09-17
- merge CLI changes for interacting with the server side (https://github.com/pulumi/pulumi/pull/20343).  I'm out 2025-09-11 - 2025-09-16, so hopefully 2025-09-17.
- turn on the feature flag more widely. Depends a bit on how the previous steps go and the amount of errors we're seeing, but hopefully 2025-10-13.

**Comment by meagancojocar** [comment]
Goal for M128 is to make progress on the service PR, review just started (we need Pat to review) but anyone on the service can also review. One more bug on the CLI side we found with fuzz testing we need to fix.
