### ISSUE TITLE
[Go Generics] Implement the pulumix [Phase 1]

### ISSUE THREAD

**Issue by abhinav** [pulumi/pulumi#13586]
Per RFC #13057, the pulumix package will contain the core, type-safe Input/Output types, combinators, and generic containers built on top of them.

All existing types in sdk/go/pulumi will implement pulumi.Input[T] for their respective types.
```[tasklist]
### Tasks
- [ ] pulumix: Add Input, Output, Apply, etc.
- [ ] pulumix: Add Apply2, Apply3, ..., Apply8 and other combinators
- [ ] pulumi: Implement pulumix.Input[T] for all built-ins
- [ ] pulumix: Add Ptr, Array, and Map containers
```
