### ISSUE TITLE
[Go Generics] SDK gen [Phase 2]

### ISSUE THREAD

**Issue by justinvp** [pulumi/pulumi#13912]
Start generating a Go SDK under `sdk/go/x/<package>` that uses `pulumix`'s generic types (`Input`, `Output`, `[G]{Ptr, Array, Map}[Output]`, etc.) instead of built-in primitive outputs (`StringOutput`, `IntOutput`, etc.) or generating container output types (no more `FooMapOutput`). Struct output wrappers should continue to be generated so that accessors are available (`FooOutput.Bar() Output[string]`).

## Tasks

- [x] Generating InvokeResult]Output type from Output[InvokeResult] and generating accessor methods for it
- [x] Generating generic SDK variants for all test schemas
- [x] Fixed secrets unwrapping and wrapping
- [x] Fixed typed accessors
- [x] Fixing default values for args
- [x] Fixing runtime errors when using object args
- [x] Go schema enum option to generate either: `none`, `side-by-side`, `generics-only`
- [ ] https://github.com/pulumi/pulumi/issues/13963
