### ISSUE TITLE
Consider improving the information density of update summaries

### ISSUE THREAD

**Issue by AaronFriel** [pulumi/pulumi#14098]
The update summaries produced by the Pulumi CLI can be verbose and challenging to read and act on. We found this was the case not just for ourselves, but in a spike on distilling information using large language models, we found that the information in update summaries was difficult to prompt engineer around.

Background on tokens: When rendering diffs for a large language model (LLM), 'tokens' are the units of information that are strictly limited. For more detail on this, refer to the [OpenAI Tokenizer](https://platform.openai.com/tokenizer) and their FAQ [What are tokens and how to count them?](https://help.openai.com/en/articles/4936856-what-are-tokens-and-how-to-count-them).

Improvements to the information density of Pulumi output summaries aren't just for AI models, though! We need to improve the readability of diffs both in the CLI and the Pulumi Cloud console. We found several situations where the current output made it difficult to understand what was occurring and why, or the output was overly verbose, with stacks emitting large numbers of near-duplicate messages for the same resource type and update.

We think a great summary would be:
* Consistent in formatting between event types. We've opened a couple issues to address that:
  * #14096
  * #14097
* Simplified, eliminating redundant or "boilerplate" lines and repetitive sections of text.
  * Detailed diffs and non-interactive summaries are hard to parse when an engine event describes multiple steps undertaken for a resource.
  * Repeated messages for the same policy violation or diagnostic across multiple resources add little value beyond the initial alert, and make it hard to identify when multiple *kinds* of policy violation or diagnostic have occurred.

## Sub-tasks

We could break this work up into a few tasks to address separately:

```tasklist
- [ ] Improve diff summary density.
- [ ] Enhance policy violation summary density.
- [ ] Improve diagnostic summary density.
```

## Summary density

The tree view displays only top-level property diffs. However, for most resources, the top-level properties are objects housing various sub-properties. 

| Display Mode | Tokens per Resource | Changes per 8k tokens |
| ----- | -----:| ---:|
| Tree | ~90 | 89 |
| Non-interactive | ~50 | 160 | 
| Non-interactive (Replacements) | ~150 | 50 | 
| Detailed diff | >300 | < 26 | 
| Detailed diff (replacements) | >900 | <9 | 

To improve density, we should consider:

* Grouping updates by type, status, and "diff", e.g., if multiple S3 buckets all have the same set of input properties changed.
  ```
   ~ (3) Updated aws:s3:Bucket my-bucket your-bucket their-bucket [diff: ~...]
  ```
* Despite capturing hierarchy, the tree view spends many tokens on spacing between columns. Could we separate the tree view from the status/diff details to get a higher density? 
  * This is more a consideration for LLMs, but it would be great to be able to augment non-interactive and detailed diffs with a tree view.
* None of the current views show the dependency relationship between resources, i.e.: the *cause* of an update or replacement.

### Examples:

```
 ~   ├─ aws:ecs:Service                   ...                   updated (4s)         [diff: ~taskDefinition]
```

In non-interactive mode, updates appear multiple times when a resource requires multiple steps to execute:

```
 ++ aws:s3:BucketObject ... create replacement[retain] [diff: ~key,source]
 +- aws:s3:BucketObject ... replace[retain] [diff: ~key,source]
 -- aws:s3:BucketObject ... delete original[retain] [diff: ~key,source]
```

However, the detailed diff includes lengthy URNs, resulting in a low signal to noise ratio:

```
    +-aws:s3/bucketObject:BucketObject: (replace)
        [id=aws-cleanup-bucket-5f639af-cleanup-func-60a4e23]
        [urn=urn:pulumi:[redacted]::infra::aws:s3/bucketObject:BucketObject::cleanup-func]
        [provider=urn:pulumi:[redacted]::infra::pulumi:providers:aws::default_5_26_0::aaf6764e-53db-4abb-b048-f8a0ad1b32f6]
      ~ detectMd5hash: "1/G0N7B2vIjFFcRD0b6cMQ==" => "different hash"
      - source       : "/tmp/pulumi-asset-6189aa5938788a69f10b4b52cebcda5b95b29a137a8369b59cc4b5bdc2749449"
      + source       : archive(assets:9f95705) {
      +     ".": archive(file:9f95705) { ../app }
        }
```

## Policy violation density

Policy violations are currently reported for each resource independently, without consolidation in any view. Users of Policy as Code, especially those dealing with a large number of advisory policies, may see text like this repeated many times within a stack. 

The current formatting uses about 80 tokens as in the example below and does not provide a robust system for consolidating or grouping similar violations.

```
    [advisory]  pulumi-internal-policies v0.0.6  s3-bucket-replication-enabled (aws:s3/bucket:Bucket: [redacted])
    Encourages use of cross-region replication for S3 buckets.
    S3 buckets should have cross-region replication.
```

## Diagnostic density

Diagnostic messages may repeat verbatim across multiple resources. In our spike, we found an instance of a stack with over 50 instances of the same warning echoed in the Diagnostics block, the only difference between messages being the URN:

```
  example:resource:name (dbtextra-USAGE):
    warning: [redacted URN] verification warning: This resource is deprecated and will be removed in a future major version release. Please use other_resource_name instead.
```
