### ISSUE TITLE
[Epic] Collect E2E coverage data for Node.js and Python SDKs

### ISSUE THREAD

**Issue by justinvp** [pulumi/pulumi#14262]
We currently only have test coverage data for the Node.js and Python SDKs based on unit tests. We don't have any data for these SDKs about coverage when running integration tests. It should be possible to enable runs of integration tests with instrumentation enabled to collect coverage data when running integration tests. This epic tracks wiring that up.

### Work Items

- [ ] POC enabling coverage instrumentation for Node.js
- [ ] Enable coverage instrumentation when running integration tests for Node.js
- [ ] POC enabling coverage instrumentation for Python
- [ ] Enable coverage instrumentation when running integration tests for Python
