### ISSUE TITLE
[Epic] Make importing resources into programs/components easier

### ISSUE THREAD

**Issue by justinvp** [pulumi/pulumi#14510]
This epic tracks a few work items around making it easier to import resources into a program or component.

First, we'll make it possible for import to create component resources to import child resources into. Next, we'll provide a way to run the user's program in a mode that finds all resources that need creating and outputting an import file filled in for those resources with all the names/urns filled in, with just the ID fields needed to be filled-in by the user. They could then run import again with that file once all the IDs have been filed in.

## M96

- [x] https://github.com/pulumi/pulumi/pull/14461
- [x] https://github.com/pulumi/pulumi/issues/14444 (wip PRs [#14467](https://github.com/pulumi/pulumi/pull/14467))
- [x] https://github.com/pulumi/pulumi/pull/14524

## M97

- [x] https://github.com/pulumi/pulumi/issues/12768 (targeting first week)
- [x] https://github.com/pulumi/pulumi/issues/14618

## M100

- [x] https://github.com/pulumi/pulumi-hugo/pull/3893
- [x] Mentioned in release notes (https://github.com/pulumi/pulumi-hugo/pull/3865). Will follow-up with it's own blog post, tracked by https://github.com/pulumi/pulumi-hugo/issues/3910

**Comment by andy-nix** [comment]
Hi @justinvp and @Frassle ,
With Pulumi 3.94 I faced with issue when importing several resources with the same name but different types leads to situation when state  has resources with wrong URN that not reflected in project code. 

As I understand this issue caused by this change https://github.com/pulumi/pulumi/pull/14524/files#diff-3bad1c9accf581bb4c47dfec524127ea7aa9ad7e597061e48e1d22929af883cfR229

`pulumi import` command when sees resources with the same name adds to each of them suffix with occurrence number (e.g. `myresource` -> `myresource_1`). It means that final URN for this resource would also have this suffix since name is part of urn (e.g. `urn:pulumi:production::acmecorp-website::custom:resources:Resource$aws:s3/bucket:Bucket::myresource_1` ). And this wrong URN written to state as result of the import.
On next stack update Pulumi sees that resource with urn `urn:pulumi:production::acmecorp-website::custom:resources:Resource$aws:s3/bucket:Bucket::myresource_1` not defined in project code and propose to destroy it, and also that resource with urn `urn:pulumi:production::acmecorp-website::custom:resources:Resource$aws:s3/bucket:Bucket::myresource` not present in state, so it should be created.
So in fact when we have at least 2 resources with the same name - import will produce wrong results.

I understand that you try to simplify import when one imported resource depends on another imported resource. And for this you are using reference by name, as most simple. But name can't be unique identificator for this. There a lot of cases when not unique name is justified. E.g. when you configuring S3 bucket versioning, ACL and other sub-configurations it is natural to give them the same name as for S3 bucket itself, to identify to what entity they belong

The only way I see to solve this issue, with saving ability to import and child and parent resource in one import command without specifying URN is to add additional temporary import ID. E.g.:

```json
{
    "resources": [
        {
            "type": "some-type",
            "name": "same-name",
            "id": "resource-id",
            "import_id": "some_unique_temporary_id"
        },
        {
            "type": "some-other-type",
            "name": "same-name",
            "id": "other-resource-id"
        },
        {
            "type": "type-token",
            "name": "name",
            "id": "resource-id",
            "parent": "some_unique_temporary_id"
        }
    ]
}
```

**Comment by Frassle** [comment]
> As I understand this issue caused by this change https://github.com/pulumi/pulumi/pull/14524/files#diff-3bad1c9accf581bb4c47dfec524127ea7aa9ad7e597061e48e1d22929af883cfR229

I think this effect is from an older change, that was trying to solve https://github.com/pulumi/pulumi/issues/6032.

> I understand that you try to simplify import when one imported resource depends on another imported resource. And for this you are using reference by name, as most simple. But name can't be unique identificator for this. 

But yes, while this current behavior is _probably_ better than a hard error its still wrong in most cases. I've been looking at how to fix it but it's tricky given how the import file is currently heavily based around assuming names are unique.

> The only way I see to solve this issue, with saving ability to import and child and parent resource in one import command without specifying URN is to add additional temporary import ID. E.g.:

This is probably not the right way to do this, but it's a very good suggestion and I think I can build something correct from it.

**Comment by Frassle** [comment]
https://github.com/pulumi/pulumi/pull/15199 plumbs in the new import features to the plugin system.

Remaining tasks after that merges:

- Update tf converter to not mangle resource names
- Update tf converter to import modules as components
- Update docs
- Blog post

**Comment by justinvp** [comment]
Closing this epic as complete. Initial docs have been published (https://github.com/pulumi/pulumi-hugo/pull/3893) and the capability was mentioned in the release notes (https://github.com/pulumi/pulumi-hugo/pull/3865). https://github.com/pulumi/pulumi-hugo/issues/3910 tracks doing a separate blog post.
