### ISSUE TITLE
Automation API support for environments

### ISSUE THREAD

**Issue by EvanBoyle** [pulumi/pulumi#14512]
We've had several users ask about environments integration with Automation API. So far we've heard two use cases:

1. programmatically setting the environment used for a stack, both as a part of creating new stacks and before operating on existing stacks. 
2. CRUD operations over environments

(2) might be better served through https://github.com/pulumi/esc/issues/60, but we should think about the full story and how they play together. 

```[tasklist]
### Tasks
- [ ] https://github.com/pulumi/pulumi/issues/14793
- [ ] https://github.com/pulumi/pulumi/issues/14794
- [ ] https://github.com/pulumi/pulumi/issues/14795
- [ ] https://github.com/pulumi/pulumi/issues/14796
- [ ] https://github.com/pulumi/pulumi/issues/14797
```

```[tasklist]
### Dependencies
- [ ] https://github.com/pulumi/pulumi/issues/14774
```

**Comment by JonParton** [comment]
I was looking for Use Case 1 so just throwing in some support 👍
