### ISSUE TITLE
[Epic] Install Pulumi CLI from Automation API

### ISSUE THREAD

**Issue by julienp** [pulumi/pulumi#14987]
We want to provide a way for the Automation API to install the Pulumi CLI so that Automation API can be used in a more standalone manner.

- [x] Update installation scripts to take an install-root option https://github.com/pulumi/get.pulumi.com/pull/171
- [x] Make SDK version available outside of binaries https://github.com/pulumi/pulumi/pull/15185
- [x] Extend Automation API with new functionality to run the installation scripts
  - [x] NodeJS https://github.com/pulumi/pulumi/pull/14991
  - [x] Golang https://github.com/pulumi/pulumi/pull/15049
  - [x] Python https://github.com/pulumi/pulumi/pull/15204
  - [x] Dotnet https://github.com/pulumi/pulumi-dotnet/pull/226
  - [ ] Release pulumi-dotnet

**Comment by justinvp** [comment]
Closing as complete. We'll publish a new .NET SDK release this week.
