### ISSUE TITLE
[Epic] Parameterized Providers

### ISSUE THREAD

**Issue by justinvp** [pulumi/pulumi#15207]
Add support for "parameterized" providers (see https://github.com/pulumi/pulumi/issues/12536#issuecomment-1488219136).

Related issues: https://github.com/pulumi/home/issues/1450

## Design

- [x] Design doc (internal: https://docs.google.com/document/d/1QT9o4gQNwNUpd85lsHV_hfqMaoHK_Ou5-pN1fs57IRQ/edit)

### M104

- [x] Provider interface (https://github.com/pulumi/pulumi/pull/16174)

### M105

- [ ] "Replacement parameterization" (for tf-bridge):
    - [ ] Engine support ([WIP PR](https://github.com/pulumi/pulumi/pull/16152))

### M106

- [ ] "Replacement parameterization" (for tf-bridge, continued):
    - [ ] Go SDK + SDKgen support
    - [ ] Node.js SDK + SDKgen support
    - [ ] Python SDK + SDKgen support
    - [ ] .NET SDK + SDKgen support
    - [ ] YAML SDK
    - [ ] Java SDK + SDKgen support

### Next quarter

- [ ] "Extension parameterization" (for K8s crds)
    - [ ] Engine
    - [ ] SDK + SDKgen

## Announce

Need to align docs and blog post announcement with how this can be used for TF providers

- [ ] Docs
- [ ] Blog post
- [ ] :icecream:
