### ISSUE TITLE
Python 3 Tracking Issue

### ISSUE THREAD

**Issue by swgillespie** [pulumi/pulumi#1535]
This issue tracks the things that need to be done to enable the use of our Python SDK with Python 3.

Currently, the Python SDK is Python 2 only. This was done for MVP expedience and going forward we are going to need to support Python 3.

## Concrete issues

* [x] https://github.com/pulumi/pulumi/issues/1541 - Python SDK should use not use implicit relative imports anywhere
* [x] https://github.com/pulumi/pulumi-terraform/issues/184 - Python generated code should use not use implicit relative imports anywhere
* [x] https://github.com/pulumi/pulumi/issues/1540 - Python SDK should test against `six.text_types` for string type checks
* [x] https://github.com/pulumi/pulumi/issues/1542 - sys.stderr.write does not show in Pulumi diagnostics
* [x] https://github.com/pulumi/pulumi-terraform/issues/183 - Python generated code should test against `six.text_types` for string type checks
* [ ] https://github.com/pulumi/pulumi/issues/1123 - Implement get factory methods for Python
* [x] https://github.com/pulumi/pulumi/issues/1735 - Invoke calls should allow passing `parent`
* [x] https://github.com/pulumi/pulumi/issues/1713 - Expose provider resources in Python
* [x] https://github.com/pulumi/pulumi/issues/1736 - Infer `provider` and `protect` defaults from `parent`
* [ ] https://github.com/pulumi/pulumi/issues/1641 - Python programs aren't modules
* [ ] https://github.com/pulumi/pulumi/issues/1064 - Implement Python closure serialization.
* [x] https://github.com/pulumi/pulumi/issues/1063 - Support outputs and dependencies in Python runtime
* [x] https://github.com/pulumi/pulumi/issues/2138 - Fix and re-enable Python integration tests
* [ ] https://github.com/pulumi/pulumi-terraform/issues/168 - Consider putting PEP-484 type hints on Python generated classes and functions 
* [x] https://github.com/pulumi/pulumi-terraform/issues/271 - Python: Property default values override provided values
* [ ] https://github.com/pulumi/pulumi-kubernetes/pull/256 - Python: Auto-generate camel case mapping table from OpenAPI spec
* [x] https://github.com/pulumi/pulumi/issues/2162 - Fix implementation of Invoke for Python 3
* [x] https://github.com/pulumi/pulumi/issues/2163 - Implement RegisterResourceOutputs for Python 3
* [x] https://github.com/pulumi/pulumi/issues/2174 - Python: 'ConfigMissingError' object has no attribute 'message'
* [x] https://github.com/pulumi/pulumi-terraform/issues/276 - Python: Properties come back from tfbridge in camel case 
* [ ] https://github.com/pulumi/pulumi/issues/2189 - Python: exceptions during property serialization can cause deadlocks
* [x] https://github.com/pulumi/pulumi/issues/1542 - sys.stderr.write does not show in Pulumi diagnostics
* [ ] https://github.com/pulumi/pulumi/issues/2320 - Support `config.getObject`

**Comment by joeduffy** [comment]
> Do we want to be able to use Python 3 features (e.g. async/await) if they are available?

I would say, emphatically, yes! :+1:

**Comment by lukehoban** [comment]
> > Do we want to be able to use Python 3 features (e.g. async/await) if they are available?
> I would say, emphatically, yes! 👍

I'm not sure I understand this question or response.  Do we want Pulumi Python users to be able to use `async/await` and other Python 3 features where they feel like it?  Of course.  Do we want the API design of the Pulumi SDK to encourage/require use of `async/await` or other features?  Not sure - will depend a lot on the details of the proposed API design for outputs (I assume that is where we are imagining async/await might become relevant?).  More important is a simple an idiomatic API design that works nicely for both Python 2 and Python 3 users.

**Comment by swgillespie** [comment]
>  More important is a simple an idiomatic API design that works nicely for both Python 2 and Python 3 users.

Yeah, that's sort of what I was getting it (in a really unclear way). `asyncio` was a huge paradigm shift in Python I/O and it's only available to Python 3. `tornado` exists and has a similar-enough API surface area that it could probably stand-in for `asyncio` with a little bit of abstraction. I'm sure that we're not the only people who have this problem so perhaps there's even a library out there that does this already.

>  Not sure - will depend a lot on the details of the proposed API design for outputs (I assume that is where we are imagining async/await might become relevant?).

Outputs are part of it, but I think the core of the question is: does Python block every time it interacts with the engine? If not, what sort of interface do we present to Python code? Twisted (all Pythons), asyncio (> Python 3.4), and `concurrent.futures` (> Python 3.2, backported to Python 2) all provide implementations of a Future class which we could use for this sort of thing, but each one is slightly different from the other and it's going to take some thought to figure out what to do so that we can play nicely with Python 2 while still allowing people to `await` a Future in Python 3.5 or above.

**Comment by swgillespie** [comment]
Some links:

* https://docs.python.org/3/library/asyncio.html
* https://docs.python.org/3/library/concurrent.futures.html
* http://www.tornadoweb.org/en/stable/index.html

**Comment by swgillespie** [comment]
I updated the checklist with issues that I uncovered today while trying to push Python 3 as far as possible. I got blocked by the codegen issues in `pulumi-terraform`.

There's a fair amount to do here. I also feel like we need to bring up language host tests for Python before embarking on this in earnest, since we're not going to be confident that everything works with Python 3 unless we test the SDK heavily.

**Comment by swgillespie** [comment]
Also I'd like to plug https://github.com/pulumi/pulumi/issues/1537 again as desirable for this work. Our build system only supports Python 2 and we're going to have to make major changes to our build scripts to support Python 3.

**Comment by joeduffy** [comment]
Note: use `asyncio` futures for Python 3 support.

**Comment by geekflyer** [comment]
small comment: please use python 3.6++ type hints for the library if possible. Makes use safer and gives better code completion.

**Comment by swgillespie** [comment]
Now that https://github.com/pulumi/pulumi/pull/2111 has merged we're well on our way to officially supporting Python 3.6+ in the next release. The linked PR is a fully-functional and parallel Python 3.6+ SDK (with type hints @geekflyer!), but the first cut is a little rough and requires a little bit of engineering discipline before it ships in earnest.

As part of this issue I will be tracking issues that we need to address before we ship a Python 3.6 SDK. I'll be editing the original post to track these.

**Comment by lukehoban** [comment]
We delivered initial support for Python3 in the `0.16.4` release.  https://pulumi.io/reference/changelog.html#v164 :tada:

We'll move this tracking issue to M20 now (along with all the related issues), but will opportunistically address some of the items here earlier where possible.

**Comment by swgillespie** [comment]
Python 3 has come along enough that I consider the "bringup" task to be complete. There's still a variety of Python-related tasks to complete, but at this point we're doing quite well with core functionality and I don't think we need a centralized tracking issue to keep track of them all.

Closing this out in favor of individual issues.
