### ISSUE TITLE
[Epic] Performance at Scale

### ISSUE THREAD

**Issue by justinvp** [pulumi/pulumi#15517]
This epic tracks some of the "Performance at Scale" issues we aim to address:

- [ ] https://github.com/pulumi/pulumi/issues/3302
- [ ] https://github.com/pulumi/pulumi/issues/13502
- [x] https://github.com/pulumi/pulumi/issues/15538

**Comment by lunaris** [comment]
Closing this as the epic for checkpointing is the only real outstanding issue; we have (opt-in) parallel `Diff` as of #18872.
