### ISSUE TITLE
[Epic] Ensure PRs don't regress test coverage

### ISSUE THREAD

**Issue by justinvp** [pulumi/pulumi#15590]
This epic tracks engineering work to make it possible to ensure PRs don't regress test coverage.

### M101

Fix known CI bugs and test flakes and turn off gotestsum retries

- [x] https://github.com/pulumi/pulumi/issues/15445
- [x] https://github.com/pulumi/pulumi/issues/15240
- [x] https://github.com/pulumi/pulumi/issues/15566
- [x] https://github.com/pulumi/pulumi/issues/15580
- [ ] https://github.com/pulumi/pulumi/issues/15274
- [ ] https://github.com/pulumi/pulumi/issues/15461
- [ ] https://github.com/pulumi/pulumi/issues/15239
- [ ] https://github.com/pulumi/pulumi/issues/15238
- [ ] https://github.com/pulumi/pulumi/issues/15237
- [ ] https://github.com/pulumi/pulumi/issues/15236
- [ ] https://github.com/pulumi/pulumi/issues/15235
- [ ] https://github.com/pulumi/pulumi/issues/14992
- [ ] Pin linters and other tools
- [ ] Disable gotestsum retries for reliable coverage data

(Some of this may carry over into M102)

## M102

- [ ] Run full set of tests on PRs

## M103

- [ ] Gate PRs on coverage
