### ISSUE TITLE
RemoteDeployment in Automation API does not allow setting executorImage (ExecutorContext) when creating a remote stack

### ISSUE THREAD

**Issue by automagic** [pulumi/pulumi#15693]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

The API seems to be lagging behind the UX and REST API, where we can set the ExecutorContext to override executorImage with a custom image (as defined here):

https://www.pulumi.com/docs/pulumi-cloud/deployments/api/#executorcontext

### Affected area/feature

Automation API - Remote Deployment (RemoteStack)
```[tasklist]
### Tasks
- [x] [Go support](https://github.com/pulumi/pulumi/issues/16277)
- [ ] [Python support](https://github.com/pulumi/pulumi/pull/19304)
- [x] [NodeJS support](https://github.com/pulumi/pulumi/pull/19286)
- [ ] C# support
```

**Comment by komalali** [comment]
Unassigning myself because I jumped on go to unblock a customer but don't have capacity to take on the remaining languages.
