### ISSUE TITLE
[Epic] Components as Components

### ISSUE THREAD

**Issue by justinvp** [pulumi/pulumi#15939]
## Overview

This epic tracks the improvements we are making to the sharing and reusability of components. 

### Feature readiness grid to dogfood

languages ready to dogfood for authoring components

| Language    | State    | Estimated Date | Docs |
|------------|---------|---------------|------|
| TypeScript |   Ready     |              |   [README](https://github.com/pulumi/pulumi/blob/master/sdk/nodejs/provider/experimental/ComponentProvider.md)   |
| Python     |     Ready    |             |   [README](https://github.com/pulumi/pulumi/blob/master/sdk/python/lib/pulumi/provider/experimental/ComponentProvider.md)   |
| Go         |    Use pulumi-go-provider    |        N/A       |   [Repo](https://github.com/pulumi/pulumi-go-provider)   |
| .NET         |    Ready     |              |   [Example](https://github.com/mikhailshilkov/comp-as-comp/tree/main/dotnet)   |
| Java       |    Ready    |               |   No   |
| YAML       |    Not ready     |        March 18       |   No   |

### References 📔

- [x] [PRFAQ](https://docs.google.com/document/d/1EynNPuBAkGLm6MEAn_k2lPFgOWvz3IhYEAxD0eHmuIU/edit?tab=t.0#heading=h.wuejtpx8p1ik)
- [x] [Design Doc](https://docs.google.com/document/d/13KNzSHXAh3HEx9VTwjbP6sR8xozrwDL6tSECvBf6bbg/edit?tab=t.0#heading=h.7fy6hfk1om6i)
- [x] [Project View](https://github.com/orgs/pulumi/projects/171)
- [x] [Old Design Doc (Internal)](https://docs.google.com/document/d/1282iElLnIBPzu1LmZo2bOm5V2AU4SLgY1INX2fyYxXo/edit)
- [x] Related Issues
    - https://github.com/pulumi/pulumi/issues/16009
- [x] [Hackathon project](https://github.com/pulumi/pulumi/tree/hackathon_substack)

#### CLI

- [x] https://github.com/pulumi/pulumi/issues/18197
- [x] https://github.com/pulumi/pulumi/issues/18281
- [x] https://github.com/pulumi/pulumi/issues/18199
- [x] https://github.com/pulumi/pulumi/issues/18250
- [x] https://github.com/pulumi/pulumi/issues/18251

#### TypeScript

- [x] Prototype schema inference approach from TS types https://github.com/pulumi/pulumi/pull/17847
- [x] 1 component package published

#### Python

- [x] https://github.com/pulumi/pulumi/issues/18288
- [x] [Prototype schema inference approach from Python types](https://github.com/pulumi/pulumi/issues/18198)
- [x] 1 component package published

#### .NET

- [x] Verify RunPlugin implementation

#### Go
- [x] Verify RunPlugin implementation

#### CLI

- [x] https://github.com/pulumi/pulumi/issues/18344
- [x] https://github.com/pulumi/pulumi/issues/18369
- [x] https://github.com/pulumi/pulumi/issues/18455

#### TypeScript

- [x] https://github.com/pulumi/pulumi/issues/18367

#### Python

- [x] https://github.com/pulumi/pulumi/issues/18366
- [x] https://github.com/pulumi/pulumi/issues/18372
- [x] https://github.com/pulumi/pulumi/issues/18347
- [x] https://github.com/pulumi/pulumi/issues/18422
- [x] https://github.com/pulumi/pulumi/issues/18438
- [x] https://github.com/pulumi/pulumi/issues/18421
- [x] #18467
- [x] https://github.com/pulumi/pulumi/issues/18458
- [x] #18482
- [x] #18508
- [x] https://github.com/pulumi/pulumi/issues/18532
- [x] https://github.com/pulumi/pulumi/issues/18530
- [x] https://github.com/pulumi/pulumi/issues/18209

#### Java

- [x] https://github.com/pulumi/pulumi-java/issues/1606

#### .NET

- [x] https://github.com/pulumi/pulumi-dotnet/pull/453

#### Docs and Registry

- [x] Design doc on required changes in Registry: https://docs.google.com/document/d/13KNzSHXAh3HEx9VTwjbP6sR8xozrwDL6tSECvBf6bbg/edit?tab=t.o44y39l1qbj4

#### YAML

- [x] Design doc for YAML components: https://docs.google.com/document/d/13KNzSHXAh3HEx9VTwjbP6sR8xozrwDL6tSECvBf6bbg/edit?tab=t.7t9s8avdojm0#heading=h.93a4svgfpqhr

#### TypeScript

- [x] https://github.com/pulumi/pulumi/issues/18365

#### CLI

- [x] https://github.com/pulumi/pulumi/issues/18557
- [x] https://github.com/pulumi/pulumi/issues/18547
- [x] https://github.com/pulumi/pulumi/issues/18529
- [x] https://github.com/pulumi/pulumi-yaml/issues/715
- [x] https://github.com/pulumi/pulumi/issues/18701
- [x] https://github.com/pulumi/pulumi/issues/18785
- [x] https://github.com/pulumi/pulumi/issues/18805

#### Python

- [x] https://github.com/pulumi/pulumi/issues/18646
- [x] https://github.com/pulumi/pulumi/issues/18714

#### .NET

- [x] https://github.com/pulumi/pulumi-dotnet/issues/468
- [x] https://github.com/pulumi/pulumi-dotnet/issues/469

#### Java

- [x] https://github.com/pulumi/pulumi-java/issues/30
- [x] https://github.com/pulumi/pulumi-java/issues/1335
- [x] https://github.com/pulumi/pulumi-java/issues/1674
- [x] https://github.com/pulumi/pulumi-java/issues/1675
- [x] 1+ component package published

#### CLI

- [x] https://github.com/pulumi/pulumi/issues/18535
- [x] https://github.com/pulumi/pulumi/issues/18624
- [x] https://github.com/pulumi/pulumi/issues/18918
- [x] https://github.com/pulumi/pulumi/issues/18778
- [x] https://github.com/pulumi/pulumi/issues/18877

#### TypeScript

- [ ] https://github.com/pulumi/pulumi/issues/18960

#### Python

- [x] https://github.com/pulumi/pulumi/issues/18846
- [x] https://github.com/pulumi/pulumi/issues/18625
- [x] https://github.com/pulumi/pulumi/issues/18692
- [ ] https://github.com/pulumi/pulumi/issues/18694
- [ ] https://github.com/pulumi/pulumi/issues/18882
- [x] #18969

#### YAML

- [x] https://github.com/pulumi/pulumi-yaml/issues/744
- [x] https://github.com/pulumi/pulumi-yaml/issues/745
- [x] https://github.com/pulumi/pulumi-yaml/issues/746
- [x] https://github.com/pulumi/pulumi-yaml/issues/755

#### Docs

- [x] https://github.com/pulumi/pulumi/issues/18370
- [x] High-level docs
- [x] Component authoring docs for each language
- [ ] Migration guide from boilerplate repos 
- [x] Launch materials

### After March launch

- [ ] https://github.com/pulumi/home/issues/3893
- [ ] https://github.com/pulumi/pulumi/issues/18638
- [ ] https://github.com/pulumi/pulumi/issues/18018
- [ ] [Add SDK types to represent Pulumi Schema](https://github.com/pulumi/pulumi/issues/18203)
- [ ] Boilerplate/bootstrap/template to make a new component
- [ ] https://github.com/pulumi/pulumi/issues/18410
- [x] https://github.com/pulumi/pulumi-yaml/issues/737

#### TypeScript

- [x] https://github.com/pulumi/pulumi/issues/18623
- [x] https://github.com/pulumi/pulumi/issues/18692
- [ ] https://github.com/pulumi/pulumi/issues/18973
- [ ] #18598
- [ ] #18601
- [ ] https://github.com/pulumi/pulumi/issues/18208
- [x] Automatic component inference from code without an explicit provider implementation
- [ ] Package as a binary - document available options and our recommendation

#### Python

- [ ] #18484
- [ ] #18481
- [ ] https://github.com/pulumi/pulumi/issues/18526
- [ ] https://github.com/pulumi/pulumi/issues/18586
- [ ] Automatic component inference from code without an explicit provider implementation
- [ ] Package as a binary - document available options and our recommendation
- [ ] Review schema inference performance

#### .NET

- [ ] Automatic component inference from code without an explicit provider implementation
- [ ] Package as a binary - document available options and our recommendation

#### Java

- [ ] https://github.com/pulumi/pulumi-java/issues/1738
- [ ] Automatic component inference from code without an explicit provider implementation
- [ ] Package as a binary - document available options and our recommendation
- [ ] Conformance tests

#### YAML

- [ ] https://github.com/pulumi/pulumi-yaml/issues/764

#### Docs

- [ ] "Choosing the right language" docs
- [ ] "Which features to use" docs (publish binaries? publish SDKs?)
- [ ] Design doc for Provider SDKs vNext (both components and custom resources) that outlines high-level details like where SDKs are located, how they are versioned, etc

#### Registry

- [ ] Registry page for git-based components
- [ ] Publishing of git-based components

**Comment by mikhailshilkov** [comment]
The epic has shipped! https://www.pulumi.com/blog/pulumi-components/

Follow-up tasks will be tracked in https://github.com/pulumi/home/issues/4012
