### ISSUE TITLE
[Epic] Import/Convert improvements

### ISSUE THREAD

**Issue by justinvp** [pulumi/pulumi#15938]
Improve the experience of importing resources into Pulumi. We've recently made several improvements to import, including the ability to import from state from a converter plugin (e.g. `pulumi import --from terraform ./terraform.tfstate`) and importing into components. However, we have not yet made the end to end experience as good as it could be. This epic involves the following:

1. Guess dependencies using heuristics (https://github.com/pulumi/pulumi/issues/10025)
2. Batch import:
    - Automation API for batch imports
    - Document how to build import capabilities (e.g. document `ConvertState`, create a boilerplate repo for a converter plugin that supports importing state)
3. Workflow: Completing the end to end experience
4. TF Convert: Address high priority gaps/bugs in conversion and programgen

### M104

- [x] https://github.com/pulumi/pulumi/pull/16208

### M105

- https://github.com/pulumi/pulumi/issues/8237 (get started)

### M106

- [x] https://github.com/pulumi/pulumi/pull/16234

### M107

- [x] https://github.com/pulumi/pulumi/issues/8237

### M108

- [x] https://github.com/pulumi/pulumi/pull/16615
- [x] https://github.com/pulumi/pulumi/pull/16668
- [x] https://github.com/pulumi/pulumi/pull/16721
- [x] https://github.com/pulumi/pulumi/pull/16786

**Comment by justinvp** [comment]
We added Automation APIs for batched import. There's likely still overall workflow experience improvements we could make, but this epic is complete.
