### ISSUE TITLE
[Epic] Native support for Poetry for new projects

### ISSUE THREAD

**Issue by justinvp** [pulumi/pulumi#15937]
Add the ability to choose a package manager to use as part of `pulumi new`. For Python, we'd like to offer Poetry support. For Node.js, we'd like to offer a choice between `npm` and `yarn` (and possibly `pnpm` and other popular tools). When running `pulumi new`, it could prompt the user for which package manager tool to use, based on what the language host can support and finds available on `$PATH`

Related issues: pulumi/pulumi#13833 

## Design (M105)
- [x] Design doc (https://docs.google.com/document/d/1073ZXigdJGjwuwb4UlmnYcO1xt_wgOsvYZmK0Y6jTFk/edit)

### M105
- [x] https://github.com/pulumi/pulumi/issues/16285
- [x] https://github.com/pulumi/pulumi/issues/16314
- [x] https://github.com/pulumi/pulumi/issues/16309
- [x] https://github.com/pulumi/pulumi/issues/16348
- [x] https://github.com/pulumi/pulumi/issues/16299

### M106
- [x] https://github.com/pulumi/pulumi/issues/16355
- [x] pulumi/pulumi#16446
- [x] pulumi/docs#12109
- [x] https://github.com/pulumi/docs/pull/12158
- [x] Update LanguageRuntimes
  - [x] Yaml https://github.com/pulumi/pulumi-yaml/pull/593
  - [x] Java https://github.com/pulumi/pulumi-java/pull/1379
  - [x] Dotnet https://github.com/pulumi/pulumi-dotnet/pull/288
- [x] https://github.com/pulumi/pulumi/pull/16489
- [x] https://github.com/pulumi/pulumi/pull/16488

### Potential followups
- [ ] https://github.com/pulumi/pulumi/issues/16286
- [ ] https://github.com/pulumi/pulumi/issues/16287

## Announce
- [x] Documentation updates https://github.com/pulumi/docs/pull/12158
- [x] Blog post https://www.pulumi.com/blog/pulumi-loves-python/
- [x] :icecream:
