### ISSUE TITLE
[Epic] pulumi up/destroy --continue-on-error

### ISSUE THREAD

**Issue by justinvp** [pulumi/pulumi#16035]
This epic tracks adding support for a `--continue-on-error` flag to `pulumi up` and `pulumi destroy` (#3304, #14515, #13306)

## Design

- [x] Design doc

## `pulumi destroy --continue-on-error`

- [x] https://github.com/pulumi/pulumi/pull/15727
- [x] https://github.com/pulumi/pulumi/pull/15921

## `pulumi up --continue-on-error`

- [x] https://github.com/pulumi/pulumi/pull/15898
- [x] https://github.com/pulumi/pulumi/pull/15942
- [x] https://github.com/pulumi/pulumi-dotnet/pull/258
- [x] https://github.com/pulumi/pulumi/pull/15740
- [x] https://github.com/pulumi/pulumi/pull/15953
- [x] https://github.com/pulumi/pulumi-dotnet/pull/265
- [x] Update YAML SDK

## Announce

- [x] https://github.com/pulumi/pulumi-hugo/pull/4194

## Later

- [ ] Update Java SDK
