### ISSUE TITLE
Flesh out Go support

### ISSUE THREAD

**Issue by lukehoban** [pulumi/pulumi#1614]
Tracking issue for work needed to fully flesh out support for Go in Pulumi:

P1:
- [x] Fix `ReadResource` (https://github.com/pulumi/pulumi/issues/1530) (https://github.com/pulumi/pulumi/issues/3562)
- [x] Support a `go run`-style workflow (don't require install) (https://github.com/pulumi/pulumi/issues/3486)
- [x] Stronger typing for Input/Output types (https://github.com/pulumi/pulumi-aws/issues/248)
- [x] Support `all` / `pulumi.output` (https://github.com/pulumi/pulumi/issues/3487)
- [x] Support `config.getObject` (https://github.com/pulumi/pulumi/issues/3493)
- [x] First class support for defining ComponentResources (https://github.com/pulumi/pulumi/issues/3488)
- [x] Providers (https://github.com/pulumi/pulumi/issues/2149)
- [x] Invoke calls should pass parent (https://github.com/pulumi/pulumi/issues/3494)
- [x] StackReference (https://github.com/pulumi/pulumi/issues/2344)
- [x] Support `ignoreChanges` (https://github.com/pulumi/pulumi/issues/3489)
- [x] Support `aliases` (https://github.com/pulumi/pulumi/issues/2924)
- [ ] Support `transformations` (https://github.com/pulumi/pulumi/issues/3490)
- [ ] Support first-class secrets (https://github.com/pulumi/pulumi/issues/2820)
- [x] Reimplement Output more robustly, consider changing it to an `interface` (https://github.com/pulumi/pulumi/issues/3492)
- [x] Move to a "functional options"-style API (https://github.com/pulumi/pulumi/issues/3491)
- [ ] More examples (https://github.com/pulumi/examples/issues/442)
- [ ] Add tests (https://github.com/pulumi/pulumi/issues/3819)
- [ ] Figure out nice workflow for plugin distribution? (https://github.com/pulumi/pulumi/issues/1549)
- [x] DeleteBeforeReplace no wired up properly (https://github.com/pulumi/pulumi/issues/3513)
- [ ] Switch templates and examples to use Go modules (https://github.com/pulumi/pulumi/issues/3817)

P2:
- [x] lifted properties
- [ ] Implement first-class unknowns (https://github.com/pulumi/pulumi/issues/3818)
- [x] Support 'concat'/'formatting strings'
- [ ] Support closure serialization? (https://github.com/pulumi/pulumi/issues/3820)

**Comment by swgillespie** [comment]
Go support is out of scope for M21.

**Comment by joshimhoff** [comment]
@lukehoban do you have a sense of when support ignoreChanges might land? We are weighing two different implementations of an important feature. One depends on ignoreChanges; the other doesn't. The latter one has other complications tho. Knowing a rough timeline would help us make the right choice.

**Comment by lukehoban** [comment]
We are currently focusing more on Node.js and Python support, while also working on https://github.com/pulumi/pulumi/issues/2430 to provide a foundation that makes additional languages fundamentally easier to support in the future.  We are definitely open to reviewing PRs, and may be able to address one-off issues.  But it's likely that in general issues on this list may still be a few milestones out.

**Comment by joshimhoff** [comment]
Got it. How much time between milestones?

**Comment by lukehoban** [comment]
> Got it. How much time between milestones?

About a month.  https://github.com/pulumi/pulumi/milestones

**Comment by EvanBoyle** [comment]
@joshimhoff https://github.com/pulumi/pulumi/pull/3514

**Comment by joeduffy** [comment]
It's not part of the core SDK, however just a reminder that we'll want to track https://github.com/pulumi/pulumi-kubernetes/issues/70 in this overall workstream also.

**Comment by EvanBoyle** [comment]
These three are in master and will go out with the next release:

- Support passing a parent and providers for `ReadResource`, `RegisterResource`, and `Invoke` in the go SDK. [#3563](https://github.com/pulumi/pulumi/pull/3563)
- Fix go SDK ReadResource [#3581](https://github.com/pulumi/pulumi/pull/3581)
- Fix go SDK DeleteBeforeReplace [#3572](https://github.com/pulumi/pulumi/pull/3572)

**Comment by joeduffy** [comment]
I'm not sure if this is worth tracking here, but the names we generate are not "perfectly idiomatic." For instance, on `ec2.Instance`, we expose properties named `PublicIp` and `PublicDns`; these technically ought to be `PublicIP` and `PublicDNS`. Not a huge deal, but worth noting.

**Comment by joeduffy** [comment]
Should we also update our templates to use Go modules? As of this writing, they still seem to use Godep.

**Comment by lukehoban** [comment]
> Should we also update our templates to use Go modules?

Yep. Added to tracking list.

**Comment by joeduffy** [comment]
Just a reminder, we should update the docs as we improve things here. I _believe_ string interpolation is now supported in Go, but https://www.pulumi.com/docs/intro/concepts/programming-model/#outputs-and-strings still lists it as a TODO and links to this very work item.

**Comment by joeduffy** [comment]
Here's another doc issue I noticed: https://www.pulumi.com/docs/intro/concepts/programming-model/#dependson says to use `pulumi.ResourceOpt{DependsOn: []Resource{res1}}`, however, `ResourceOpt` doesn't seem to exist, and it appears the preferred approach is to use functions like `pulumi.DependsOn` to construct the options bag?

**Comment by EvanBoyle** [comment]
We do have an item to track a doc update (
https://github.com/pulumi/docs/issues/2311) but you're right, we should be
doing this as we go.

**Comment by joeduffy** [comment]
One question I have: for data source invokes, it looks like we take pointers (e.g., `*bool`, `*string`, etc). I assume this is so we know what is "missing" versus being an actual empty value (e.g., `nil` versus `false`). But it does lead to some clumsy code, like https://github.com/pulumi/examples/pull/540/files#diff-b570181547fbf47c161a97779091d852R14, unless I'm missing something. Two questions:

1) is this truly required? We don't seem to do this for `*Args` types, but I guess that's because they are `pulumi.BoolInput`-style types?
2) should we add helpers like `pulumi.BoolPtr` to make this easier?

**Comment by EvanBoyle** [comment]
cc @pgavlin ^

**Comment by pgavlin** [comment]
> is this truly required? We don't seem to do this for *Args types, but I guess that's because they are pulumi.BoolInput-style types?

It is, yes: we need to be able to distinguish between "not set" and "set to the zero value". Args types do also do this, but they are a bit easier to deal with b/c they use interface types: https://github.com/pulumi/pulumi-aws/blob/master/sdk/go/aws/s3/bucket.go#L267-L268

> should we add helpers like pulumi.BoolPtr to make this easier?

I'd love to add helpers like that, but they would overlap with the `pulumi.XPtr` input types. Any other ideas for names? Maybe put them in a subpackage?

**Comment by lukehoban** [comment]
The updated support for Go has landed in the core SDK and across the main cloud packages.  Some more work is planned on the path to GA of Go support in 2.0, which is now tracked in specific issues marked with the [language/go](https://github.com/issues?utf8=%E2%9C%93&q=org%3Apulumi+is%3Aopen+label%3Alanguage%2Fgo) label.
