### ISSUE TITLE
[Epic] Programmatic Default Providers

### ISSUE THREAD

**Issue by tgummerer** [pulumi/pulumi#16171]
Providers in pulumi can be instantiated in two different ways.  One is implicitly through the program.  If the user doesn’t set an explicit provider for a resource, the resource automatically gets a default provider assigned.  On the other hand, providers that have been created beforehand can be passed along to the resource registration request and that provider will be used to create the resource.

There is currently no way to set up a default provider for all the resources in a particular pulumi program.  This especially in combination with default providers can lead to confusion, as it’s easy to forget to pass in a provider to some resource, and then there could be multiple resources with different provider settings in the same program.  For example for the kubernetes provider, someone could carefully set one up, and then forget to pass that provider to a kubernetes resource. That would then create a new kubernetes default provider based on a local kubeconfig, which is probably not what the user wanted.

This issue is to track the work to allow users to programmatically set up a default provider for all the resources a provider supports.

Related issues: #2059 

## Design (M103)
- [ ] Write design doc for programmatic default providers

### M104
- [ ] https://github.com/tgummerer/testrepo/issues/16163
- [ ] https://github.com/tgummerer/testrepo/issues/16169
- [ ] https://github.com/tgummerer/testrepo/issues/16166
- [ ] https://github.com/tgummerer/testrepo/issues/16167

### M105
- [ ] https://github.com/tgummerer/testrepo/issues/16165
- [ ] https://github.com/tgummerer/testrepo/issues/16168

### Future
- [ ] https://github.com/tgummerer/testrepo/issues/16170

## Announce
- [ ] https://github.com/tgummerer/testrepo/issues/16164
- [ ] :icecream:
