### ISSUE TITLE
[Epic] More control over auto-naming

### ISSUE THREAD

**Issue by justinvp** [pulumi/pulumi#16188]
Lots of things in Pulumi use _autonaming_ – a feature whereby Pulumi ensures unique names for “physical” (cloud-side) resources by generating names or name suffixes. For instance, if one uses the AWS provider to write:

```typescript
const foo = new aws.rds.Instance("foo", { ... })
```

One will end up with an RDS database named (for instance) `foo-ab158dc9`. The motivations for this feature are several – being able to handle create-before-replace semantics to aid in various zero-downtime scenarios; being able to spin up multiple instances of the same stack into a single account/cloud-side presence; and so on.

If one wants to specify a resource name exactly, this can nearly always be accomplished by explicitly specifying a specific input (rather than relying on the Pulumi resource name). Often this is called `name`, but this is not always the case; for RDS instances the input is named `identifier`:

```typescript
const foo = new aws.rds.Instance("foo", { identifier: "foo", ... })
```

RDS instances also happen to offer an `identifierPrefix` input which allows some degree of control over names whilst still asking Pulumi to generate parts of the name, but this is specific to this resource. In general, to control naming, users and customers will have to think about this issue for each provider and set of resources they create.

This is not ideal, and many users and customers have wanted broad-spectrum or high-level control over how and when autonaming works for a long time.

Related issues: https://github.com/pulumi/pulumi/issues/1518

## Design

- [x] Write a design doc (internal WIP: https://docs.google.com/document/d/1ZJoxla8WId3aaJV2xqYvulcYB6a1cFfV4bbddk08pdA/edit#heading=h.jgdc2wwr5350)
- [x] Post a public RFC: https://github.com/pulumi/pulumi/discussions/17592

## Implementation Plan

- [x] https://github.com/pulumi/pulumi/pull/17810
- [x] https://github.com/pulumi/pulumi/pull/17897
- [x] https://github.com/pulumi/pulumi/pull/17916
- [x] https://github.com/pulumi/pulumi/issues/17971
- [x] https://github.com/pulumi/pulumi-terraform-bridge/issues/2722
- [x] https://github.com/pulumi/pulumi-azure-native/issues/3777
- [x] https://github.com/pulumi/pulumi-aws-native/issues/1901
- [x] https://github.com/pulumi/pulumi-kubernetes/issues/3363
- [ ] Stop gating the feature in CLI behind PULUMI_EXPERIMENTAL

## Announce

- [ ] Documentation updates for this new capability
- [ ] Write blog post announcing
- [ ] :icecream:

**Comment by MarkTallentire** [comment]
Personally i just dont think autonaming works at all. DeleteBeforeReplace should just become the standard behaviour and autonaming scrapped in favour of the name being passed to the constructor being the name used.

**Comment by Frassle** [comment]
The intention is to make that an option, but we have plenty of customers who believe the opposite and we can't safely make a break change like that now anyway.

**Comment by mikhailshilkov** [comment]
This feature has now officially shipped! You can learn more about it in my blog post: [Introducing Customizable Resource Auto-naming in Pulumi](https://www.pulumi.com/blog/autonaming-configuration/)

Thank you to everyone who provided feedback and helped shape the proposal!
