### ISSUE TITLE
[Epic] Support declaring that a resource should be created only if it does not already exist

### ISSUE THREAD

**Issue by justinvp** [pulumi/pulumi#16189]
There are some cases where there are cloud resources that are scoped to an account - like `ServiceLinkedRoles` in AWS or Project Services in GCP.  Individual deployments will frequently want to ensure the resource exists - but do not want to manage it long term.  For example:
1. If it exists, read it in so it can be referenced
2. If it does not exist, create it
3. When the Pulumi resource is deleted - don't remove from the cloud provider

Today, this can't quite be expressed in Pulumi.  In principle it would be possible to provide a `ResourceOption` which would allow expressing this.

Related issues: https://github.com/pulumi/pulumi/issues/3388

## Design

- [ ] Write design doc ([internal draft](https://docs.google.com/document/d/1UJk1dmLbALBjccy7GGBOkqNy7Jgv4dwNUr8onLY9eCw/edit#heading=h.jd467wz1rr4p))

## Implementation Plan

- [ ] Engine
- [ ] Node.js SDK
- [ ] Python SDK
- [ ] Go SDK
- [ ] .NET SDK
- [ ] YAML
- [ ] Java SDK

## Announce

- [ ] Documentation updates for this new capability
- [ ] Write blog post
- [ ] :icecream:

**Comment by Jtango18** [comment]
This sounds like it would be useful during the Dev process for me at the moment.

My scenario is that I'm testing deploying/destroying stacks multiple times to trial things. My DB server can take anywhere between 10-45 minutes to destroy or provision, so would be great to have this resource option to use during the development phase (or boolean switchable based on config).

Just another potential use case to justify this ;-)
