### ISSUE TITLE
[Epic] Support moving resources between projects

### ISSUE THREAD

**Issue by justinvp** [pulumi/pulumi#16190]
Sometimes would be useful to move some resource from one project stack to another project stack, without recreating the resource.

For example, split a monolithic stack to micro stacks.

Currently, the easiest way to move the code to the new stack and import it, then remove from the old stack manually with `pulumi state delete` or exporting the stack and removing the resource and every dependency.

This is a very error-prone process, pulumi should provide an easier way to do these kinds of refactorings.

Related issues: https://github.com/pulumi/pulumi/issues/3389

## Design

- [x] Write design doc ([internal draft](https://docs.google.com/document/d/102zS2ZVQnmJVzYpThvBz7EMq0ZmivOV5DIQ9W6QcUQw/edit#heading=h.w3e3tscn5u20))

### M106

- [x] https://github.com/pulumi/pulumi/pull/16493
- [x] https://github.com/pulumi/pulumi/pull/16523
- [x] https://github.com/pulumi/pulumi/pull/16527
- [x] https://github.com/pulumi/pulumi/pull/16538
- [x] https://github.com/pulumi/pulumi/pull/16543
- [x] https://github.com/pulumi/pulumi/pull/16562
- [x] https://github.com/pulumi/pulumi/pull/16628
- [x] https://github.com/pulumi/pulumi/pull/16630

## Announce

- [ ] Documentation updates for this new capability
- [x] Write blog post (https://github.com/pulumi/docs/pull/12286)
- [ ] :icecream:
