### ISSUE TITLE
[Epic] Better MLCs

### ISSUE THREAD

**Issue by justinvp** [pulumi/pulumi#16599]
## Overview

This epic tracks addressing some known quality issues with packaged components (MLCs).

## Key Stakeholders

EPD: @tgummerer, @justinvp, @mjeffryes, @EronWright

## Key Deliverables

Bug fixes will roll out as fixed.

### References 📔

- [x] [Project View](https://github.com/orgs/pulumi/projects/170)

### Issues

- [x] https://github.com/pulumi/pulumi/issues/13223
- [x] https://github.com/pulumi/pulumi/issues/16331
- [x] https://github.com/pulumi/pulumi/issues/15788
- [x] https://github.com/pulumi/pulumi/issues/6933
- [ ] https://github.com/pulumi/pulumi/issues/13802

**Comment by justinvp** [comment]
Closing this epic as finished. There's still the last issue (https://github.com/pulumi/pulumi/issues/13802) that we'll track on it's own; ETA this iteration.
