### ISSUE TITLE
[Epic] Run program during refresh and destroy

### ISSUE THREAD

**Issue by justinvp** [pulumi/pulumi#16600]
This epic tracks adding support for running the program during refresh and destroy (likely opt-in).

[Design doc](https://docs.google.com/document/d/1eWIbTLjdd7ac9Rp_GhnQ58fowNv6fgJlf9MaR0GKKVI/edit?pli=1&tab=t.0#heading=h.9kk33wn351pw)

## Things to think about

- [ ] Refresh
  - [x] Stub out lifecycle tests for expected behaviour of refresh with the program
    - [x] Provider resource registrations
      - [x] Provider depends on another resource
    - [x] Default providers
    - [x] Custom resource registrations
    - [x] Component resource registrations
    - [ ] `.get` / program reads
    - [ ] Transforms
      - [ ] On providers
      - [ ] On resources (can change providers too)
    - [ ] Invokes
    - [ ] Resource options (all, but specific call-outs)
      - [ ] `dependsOn`
      - [ ] `ignoreChanges`?
      - [ ] `protect`
      - [ ] `parent`/`aliases`
    - [x] `--target`
    - [ ] `--replace`/replaces/`deleteBeforeReplace` etc.?
    - [ ] `.apply`
    - [ ] Dynamic providers (not sure they need a special case)
    - [ ] Resources which receive no registrations (custom, component, provider)
    - [x] Resources that are in state but not in provider
    - [ ] Resources that are in provider but not in state
- [ ] Destroy
  - [x] Stub out lifecycle tests for expected behaviour of destroy with the program
    - [x] Provider resource registrations
      - [x] Provider depends on another resource
    - [x] Default providers
    - [x] Custom resource registrations
    - [x] Component resource registrations
    - [ ] `.get` / program reads
    - [ ] Transforms
      - [ ] On providers
      - [ ] On resources (can change providers too)
    - [ ] Invokes
    - [ ] Resource options (all, but specific call-outs)
      - [ ] `dependsOn`
      - [ ] `ignoreChanges`?
      - [ ] `protect`
      - [ ] `parent`/`aliases`
    - [x] `--target`
    - [ ] `--replace`/replaces/`deleteBeforeReplace` etc.?
    - [ ] `.apply`
    - [ ] Dynamic providers (not sure they need a special case)
    - [x] Resources which receive no registrations (custom, component, provider)
    - [x] Resources that are in state but not in provider
    - [ ] Resources that are in provider but not in state

**Comment by EronWright** [comment]
This is a counter-intuitive idea for me, because the purpose of running the program is to update its goals, and why would refresh or destroy need that? Meanwhile, the stack configuration is always updatable, right? Is the motivation related to provider configuration?

**Comment by justinvp** [comment]
> Is the motivation related to provider configuration?

Yes, that's one of the motivations. Another reason would be to support running deletion lifecycle hooks that can work during destroy.

**Comment by VenelinMartinov** [comment]
We had a discussion with @Frassle today around https://github.com/pulumi/pulumi/pull/18740 and it touched upon running the program during refresh and destroy.

One of the questions which we couldn't quite answer is how are we going to guarantee that when running the program during `refresh` we are using the correct provider version with the correct configuration.

Currently, these are both saved in the state, so both the version and configuration are the same as the last time the program was updated. If we start running the program during refresh and acquire both the default provider version and the config from the "new program" then we can't guarantee that:
1. The "new program" has the same version of the default provider as the one saved in state.
2. The "new configuration" is compatible with the default provider saved in state. The schema might have changed significantly and given how rarely users tend to upgrade their provider versions, this is almost guaranteed on provider upgrades, which is already quite challenging as is.

Have we discussed these issues around provider version upgrades? Seems like this could lead to some weird and unexpected behaviours.

**Comment by Frassle** [comment]
> If we start running the program during refresh and acquire both the default provider version and the config from the "new program" then we can't guarantee that:
> 
> 1. The "new program" has the same version of the default provider as the one saved in state.
> 2. The "new configuration" is compatible with the provider saved in state. The schema might have changed significantly. Given how rarely users tend to upgrade their provider versions, this is almost guaranteed on provider upgrades, which is already quite challenging as is.

I think 1 is the same problem as for normal `up` runs where the provider needs to handle that the "olds" it gets in Check/Diff/Update may have come from an old version of the provider. This just makes it so providers also need to worry about that for Read as well.

2 I don't think matters? The whole point is we won't be using the provider in state, we'll be using the new provider version with the new config.

**Comment by ashish111333** [comment]
@Frassle I would like help with some of these ...can I get access to the design doc.

**Comment by Frassle** [comment]
Hi @ashish111333 these were actually merged in this week. There's still some edges to finish off, it's not exposed to Automation API yet and more tests are always good, but the bulk of it is done.

**Comment by ashish111333** [comment]
@Frassle Np I was just looking to explore pulumi  repo...anything else you have got where you think I can help. I would be happy to contribute. I  am looking for some challenge.

**Comment by meagancojocar** [comment]
Closing this as we shipped it! https://www.pulumi.com/blog/improved-refresh-destroy-experience/

**Comment by alextbok** [comment]
> Closing this as we shipped it! https://www.pulumi.com/blog/improved-refresh-destroy-experience/

Will [#18765](https://github.com/pulumi/pulumi/issues/18765) and [#18760](https://github.com/pulumi/pulumi/issues/18760) still be prioritized for use in the automation api?

**Comment by Frassle** [comment]
> Will https://github.com/pulumi/pulumi/issues/18765 and https://github.com/pulumi/pulumi/issues/18760 still be prioritized for use in the automation api?

Yes, they've just been delayed a little as we see if we can work them into a new method to partially auto-generated the automation api. But we'll be looking at getting them in in the coming week.

**Comment by jelmersnoeck** [comment]
Great to see this, as it solves some access token issues we've been seeing!

Will this also be implemented for `preview` commands? In particular, when running `pulumi preview --refresh`, this still breaks the workflow if there is a dynamic token as the credentials are not being refreshed. (Doing a `pulumi refresh --run-program` and then `pulumi preview --refresh` does work).

**Comment by Frassle** [comment]
> Will this also be implemented for preview commands?

Yes, we'll add it for the preview commands as well. Only applies for `preview --refresh` but we can allow `--run-program` to be passed to turn on the new refresh logic for that.

**Comment by moredatapls** [comment]
@Frassle that would help me a lot, too. Is there an issue/epic for that that I can follow?

**Comment by Frassle** [comment]
https://github.com/pulumi/pulumi/pull/19449 will be in next release

**Comment by AngellusMortis** [comment]
Is run program for refresh supposed to run the update resource hooks? Or is that part of https://github.com/pulumi/pulumi/issues/18761? There is no description on the ticket so was not sure. 

From testing, I cannot seem to seem to get the hooks to ever run for refreshes. One of the resource hook examples is even an SSH tunnel, which needs to always before for create/update/refresh/destroy/etc.

**Comment by Frassle** [comment]
Hooks don't run during refresh currently. We'd probably need to add a new refresh/read hook type to support that.
