### ISSUE TITLE
[Epic] Parameterization: `pulumi import` support

### ISSUE THREAD

**Issue by justinvp** [pulumi/pulumi#17507]
## Overview

Support for importing resources from a parameterized provider.

Related: #17289

### Work Items

- [x] https://github.com/pulumi/pulumi/pull/17910
- [x] https://github.com/pulumi/pulumi/pull/17894
- [x] https://github.com/pulumi/pulumi-yaml/issues/701
- [x] https://github.com/pulumi/pulumi/pull/18029
- [x] https://github.com/pulumi/pulumi/pull/18038
- [x] https://github.com/pulumi/pulumi/pull/18039
- [x] https://github.com/pulumi/pulumi-dotnet/issues/432
- [x] https://github.com/pulumi/pulumi-java/issues/1510
