### ISSUE TITLE
[Epic] Adopt Conformance Tests

### ISSUE THREAD

**Issue by justinvp** [pulumi/pulumi#17505]
## Overview

Enable conformance tests for the remaining supported languages:

- [ ] [.NET](https://github.com/pulumi/pulumi-dotnet/pull/314)
- [ ] [YAML](https://github.com/pulumi/pulumi-yaml/pull/549)
- [ ] [Java](https://github.com/pulumi/pulumi-java/pull/1403)

### References 📔

- [ ] Project View 
- [ ] PR/FAQ 
- [ ] Design Doc 
- [ ] UX Designs 
- [ ] Decision Log

**Comment by justinvp** [comment]
All the languages are now running conformance tests. There are still some tests being skipped due to various bugs, but we'll tackle those individually.
