### ISSUE TITLE
[Epic] Parameterization: Conformance Tests

### ISSUE THREAD

**Issue by justinvp** [pulumi/pulumi#17506]
## Overview

Add conformance tests for parameterized providers.

## Work Items

- [x] Test parameterized packages in conformance
    - [x] https://github.com/pulumi/pulumi/pull/17929
    - [x] https://github.com/pulumi/pulumi-yaml/pull/688
    - [x] https://github.com/pulumi/pulumi/pull/17589
