### ISSUE TITLE
[Epic] Multi-language components: public preview

### ISSUE THREAD

**Issue by swgillespie** [pulumi/pulumi#2430]
Today, Pulumi programs can be written in a variety of languages, including JavaScript/TypeScript, Python, C#/F#/VB and Go.  For core cloud provider packages (like `aws` and `kubernetes`), libraries are made available to each of these languages using a schema-based code generation approach.  However, for higher level components written in one of these languages, today such components are only available to users of that same language.  This includes first party components like `awsx`, `eks` and `kx`.  But it also include components that Pulumi users build and distribute either publicly or within their organization.

Our goal is to address this, allowing Pulumi components to be authored once and consumed from any supported Pulumi programming language.  This Epic represents the core Pulumi platform work required to release a public preview of the authoring experience for multi-language components. https://github.com/pulumi/home/issues/1201 tracks the additional work to get us to GA.

**Product owner:** @infin8x

## Work items

**Cost in engineer-weeks:** TODO

### Design and specification 📔

- [x] PR/FAQ [Link](https://docs.google.com/document/d/1IKPMIlF3tup2bPq5x1Kw18nCXB3f8zB4oAIw09Ws3XQ/edit?usp=drive_web&ouid=105122965995123866593)
- [x] Identify preview customers 

### Engineering ⚙️

- [ ] Prepare guide for authoring multi-language components https://github.com/pulumi/pulumi/issues/6369
- [ ] Enable the creation of ComponentResources in all languages #5044
- [ ] Any other issues in [iteration backlog here](https://github.com/orgs/pulumi/projects/11?card_filter_query=label%3Aarea%2Fmulti-language-components+milestone%3A0.52)

### Launch readiness 🎁

**Release coordinator:** @infin8x

- [ ] Demo the feature at TGIF
- [ ] Ship it 🚀

### Old issue details

<details>
  <summary>Background on this work</summary>
We've explored many technologies that could serve as a foundation for this work (WebAssembly, JSII, JS-transpilers and more), and have ultimately decided to stick to a model closely aligned with the rest of Pulumi's existing multi-language support.

With the approach, the Pulumi resource model remains the central concept driving cross-language support.  The same schema model used for cloud provider packages will be extended to support the cross-language compatible API surface area, and the same code generators used for cloud provider packages will be used to generate per-language API interfaces to shared language components.  The API surface area will be largely constrained to the same primitives that the core Pulumi engine RPC interfaces already use - resource construction and function (and method) calls. The cross language type systems will be mostly the same as the currently support Pulumi schema model - resources, functions, POJO (JSON) types and enums.  

Concretely, we will be rolling this support out over the next few months.  Our current roadmap looks as follows (though we expect to learn more and adjust as we make progress).  The **bolded** items are the externally visible milestones along this path. 

(Plan updated 11/3/2020 to remove extraneous items such as code generation, which have largely been addressed already):

11/11/2020:
Ship eks package for Python, .NET, and Go

11/28/2020:
Remote function calls
Ship eks package for Node (parity with other packages)
3rd Party Authoring/Publishing Support

-----
**Original Issue Description and Background**

Today, Pulumi is officially capable of hosting programs written in JavaScript/TypeScript, Python, and Go. It is also capable of running programs written in [C# and F#](https://github.com/pulumi/pulumi/pull/2003). Pulumi advertises itself as a multi-language system and, indeed, we have spent a lot of engineering time and effort ensuring that Pulumi supports more than one language.

Supporting multiple languages is an adoption boon. Pulumi itself is a new programming model and, if a user does not already know the language that they are using with Pulumi, it becomes a hugely daunting task to learn both a new language and Pulumi's programming model simultaneously. If Pulumi supports a language that a user already knows, it becomes much easier to understand how Pulumi works and how to use it effectively.

However, we have found that the maintenance cost of multiple language frontends for Pulumi is very high. We have put a large amount of engineering effort towards [bringing our Python support to feature-parity with NodeJS](https://github.com/pulumi/pulumi/issues/1535), as @Frassle also has done for .NET. As it stands today it is difficult for us as a small group of engineers to scale effectively when our efforts must be spread out and duplicated across languages.

Furthermore, Pulumi users and those of us working at Pulumi alike have built a number of useful high-level libraries. ([1](https://github.com/pulumi/pulumi-eks) [2](https://github.com/pulumi/pulumi-awsx) [3](https://github.com/pulumi/pulumi-cloud) [4](https://github.com/pulumi/pulumi-docker)). These libraries encapsulate into reusable components tasks that are otherwise hard to do, such as creating EKS clusters, creating AWS best-practice network topologies, and orchestrating Docker builds. It is clear that part of Pulumi's "magic" is the ability to author reusable components in a real programming language and be able to publish them through normal code push mechanisms such as NPM or PyPI.

Having said all of this, a clear contradiction in the "Pulumi story" arises: reusable components can only be used if the component is implemented in the same language that a user is using with Pulumi. A user today writing Pulumi programs in Python can't use any of the above linked packages and must re-write them wholesale in order to get any value from them. We are acutely aware of this issue.

## Current State

Today, Pulumi supports a few languages, but none of the libraries written in those languages can be reused unless you're using the same language. Because the Pulumi team has invested a large majority of their engineering time and effort in TypeScript, all of our high-level libraries are written in TypeScript and can only be consumed by Pulumi programs written in TypeScript or JavaScript. Pulumi programs written in Python or Go have essentially zero libraries.

We do not believe that the "status quo" is sustainable at its current rate. We do not have the engineering bandwidth to manually duplicate all high-level libraries that we provide across all supported languages. Even if we did, the combinatorial explosion of language-library pairs makes it harder and harder to add additional languages to Pulumi as Pulumi's ecosystem as a whole grows.

## Short-term Plan

In the M21 timeframe (the next 5 weeks), we plan on pursuing a prototype for "multi-language interop" - the ability for a component authored in one language to be used naturally in another language. The goal of this prototype is to write a Pulumi program in Python that creates an EKS cluster using the `@pulumi/eks` package, which is itself authored in TypeScript. This is an R&D effort. The goal here is to investigate what the prototype solution looks like and how it fits into the rest of the Pulumi ecosystem.

In the short-term, we are not going to put any engineering effort into Go language support for Pulumi. The hope is that, by pursuing a prototype, we will unlock a path to multi-language interop that will reduce the cost of adding additional languages to Pulumi so that we can once more accept additional languages into the Pulumi ecosystem.

## Long-term Plan

At the end of the M21 timeframe, we will evaluate the R&D effort and make a decision about Pulumi's multi-language story. The various axes that we will consider include:

1. The prevalence of new component libraries and their usage
2. Whether or not the prototype accomplished its primary goal of interoperating with `@pulumi/eks`
3. Whether or not the prototype accomplished its secondary goals of producing a general system and scheme for interoperating languages and libraries
4. The estimated time cost of productizing the prototype based on our experience creating it 

The are multiple options on the table with regards to Pulumi's multi-language story going forward, which we must decide on:

1. "Status quo". After pursuing the prototype and finding it lacking or infeasible for whatever reason, we will continue as we are today, supporting multiple languages that do not interoperate with one another. We will do the work to re-write commonly used component libaries in languages that need them, driven by user demand.
2. Productize the multi-language interop prototype with the goal of authoring a set of component libraries in a single language that can be used from multiple languages.
3. Drop support for languages other than JavaScript/TypeScript.

## Prototype Plan

In M21, @swgillespie will pursue a prototype that allows language hosts to launch other language hosts, remote objects across process boundaries, and launch instances of libraries in those child language hosts. The goal of the prototype is to allow for the invoking of constructors and the invoking of functions across language boundaries. We have put a lot of thought into candidate designs for a prototype and this design is the one that has shown the most promise.

The goal of the prototype is to instantiate a `@pulumi/eks` `Cluster` resource in a Python program. This involves creating a way for the Python language host to launch a NodeJS language host, load the `@pulumi/eks` library in the target language host, pass arguments to the `Cluster` constructor, and receive outputs from the created `Cluster` object. The goal is explicitly not to create a general-purpose remote object protocol.

If the prototype is successful and we choose to productize it, the goal will be to produce a way for us as Pulumi engineers to author libraries that can be used in languages other than the implementation language. As it matures, the interop system may also be usable by Pulumi users so that they can author their own components.

</details>

**Comment by RobJellinghaus** [comment]
I know statically typed languages aren't really in your wheelhouse atm, but I couldn't help noticing the similarity to [xlang](https://github.com/Microsoft/xlang/blob/master/design_notes/XDN01%20-%20A%20Strategy%20for%20Language%20Interoperability.md).

> Components are written using the type system of the implementation language and accessed using the type system of the consuming language. As such, the xlang type system is designed to interoperate with modern object-oriented programming languages. This includes both static (such as C#) and dynamic (such as Python) object-oriented languages as well as strongly typed (such as C++) and weakly typed (such as JavaScript) languages.

**Comment by pchalamet** [comment]
Couldn't you just consider terraform as an internal pivot format for infrastructure description on which all lang could interrop? Did a POC last year (https://github.com/pchalamet/NTerraform): that was based on terraform providers to generate a lang bridge. Idea was to implement a type provider then in f# above but never really had time to go beyond this after vacations. Authoring experience is far better when you are taken by hand in the IDE and it's far better than yaml.
I do not know inner internals of pulumi but I guess it used to be bootstrapped like this at some point. Just speculating.

But yes, in contrast, this requires a lot of code generators and requires to extract metadata from terraform providers. But this can be automated and made available to most lang and looks like it's no big deal - it's just a matter of build steps and caching I would say (not saying it's easy). Drawbacks are you can't natively interrop with functions as pulumi requires it. So couldn't functions be pushed to well, just functions (azure functions for eg) or a docker? Pulumi could take care of all this plumbing with much benefits for users.

I do no have much to bring to the table, sorry. I'm just curious about your prototype and how you will solve this!

**Comment by swgillespie** [comment]
> I know statically typed languages aren't really in your wheelhouse atm, but I couldn't help noticing the similarity to [xlang](https://github.com/Microsoft/xlang/blob/master/design_notes/XDN01%20-%20A%20Strategy%20for%20Language%20Interoperability.md).

xlang is a general-purpose remote object protocol, which (while useful) is far more powerful than we need and is generally counter to our goals:

> The goal is explicitly not to create a general-purpose remote object protocol.

xlang (and it's predecessors, WinRT and COM) are very heavyweight. An explicit design goal is to produce something that is as lightweight as possible.

> Couldn't you just consider terraform as an internal pivot format for infrastructure description on which all lang could interrop?

We do not want to tie ourselves to Terraform in the long run. We already do not use Terraform for our Kubernetes provider. In general, the fact that Pulumi uses Terraform providers at all is an implementation detail.

> But yes, in contrast, this requires a lot of code generators and requires to extract metadata from terraform providers. But this can be automated and made available to most lang and looks like it's no big deal - it's just a matter of build steps and caching I would say (not saying it's easy).

We already do this: https://github.com/pulumi/pulumi-terraform. We have a tool called `tfgen` that extracts metadata from Terraform providers and generates code from them. You're right that this already "solves" the problem and, in fact, it's really the crux of how we've even gotten this far in the first place. However, it also intimately chains us to Terraform in a way that is not desirable.

**Comment by Frassle** [comment]
Is there a branch we can watch to get an idea of how this is coming along?

**Comment by swgillespie** [comment]
@Frassle not yet, but stay tuned!

**Comment by swgillespie** [comment]
Hi all, here's an update:

Our M21 timeframe is wrapping up today, and with it the R&D experiment that I mentioned in the OP. The primary goal of this exercise was to produce a prototype that was able to, from within a program written in Python, interoperate with the `@pulumi/eks` JavaScript package - and from that perspective, the experiment was mostly successful. The code for this is in another repository that isn't public for purely logistical reasons - I expect that as we proceed in M22 this code will either be open sourced directly or integrated into this repo.

The next step here is to move on to the decision-making portion of the task that I pointed out in the OP. In the M22 timeframe we're going to take a look at where we ended up and make a judgement call about what to do next. The plan hasn't changed since I wrote the OP.

**Comment by Frassle** [comment]
Any more updates on this? I'm hoping the python blog post last week is a positive sign for supporting multi-language.

**Comment by swgillespie** [comment]
No updates since the last. Unfortunately we haven't had the time to dedicate to this. I have still been working on Python support but I have not had the time to pursue the things in this issue.

**Comment by Frassle** [comment]
Aw that's a shame but understood. We we're holding out a bit hoping we could use F# with Pulumi as we've got much better infrastructure around .NET code and NuGet than we do javascript and npm. But we'll probably just bite and go with TypeScript for now, should still be an improvement over all the helm and powershell we've got at the moment.

**Comment by knocte** [comment]
ping? I'd be interested in F# support too

**Comment by varon** [comment]
Still waiting for any dotnet on this side. Preferably F# too.

**Comment by Frassle** [comment]
I'm still around to help with getting #2003 good if dotnet gets the go ahead. TypeScript isn't bad but we would still love to write k8s setups with F#.

**Comment by joeduffy** [comment]
Apologies for the delay on this, folks. Needless to say, this is a tricky -- but important -- area for us. Now that 1.0 is out the door, we're focused on coming up with a 2.0 roadmap and as part of that, we will have a definitive answer on next steps here. We appreciate the patience 🙏

**Comment by lukehoban** [comment]
Updated the title to reflect the goals here.  Pulumi already supports many languages, and we continue to add new ones (like .NET!).  However, today higher level libraries/packages must be developed independently for each language they want to be made available in.  The work tracked here is to have a way to use a Pulumi library authored in one language from a program written in another language.  This will unify the library ecosystems for Pulumi across all languages.

**Comment by brandonkal** [comment]
For what it is worth, I would suggest focusing on just JavaScript/TypeScript to avoid stretching yourselves to thin. I understand the desire to support develop many high-level packages for other languages, but at least from my outside perspective it is not providing value that matches the required effort for one team to maintain.

I very much like Go. But I am writing all of my Pulumi code in TS because it is clear that is where the best library support is. It also naturally works quite well with creating JSON-like objects.

I'm not finding anything lacking in using Node as the runtime here that would give me a reason to switch to Go if it becomes on par with your node support. JS is the _lingua franca_ now and I have a hard time believing someone who prefers another language for their application code would have a hard time understanding a JS Pulumi program. It very much feels like the right tool for the job for this case, and there is not much another language brings here besides a different syntax.

Doing this would have some benefits:
- More libraries available. If everyone uses one language for this new paradigm in cloud programming, we'll all be more efficient. No need to port a great outside .NET/Python library to use in a JS Pulumi Program. Less duplicated work for everyone as a whole and more reusable code.
- More time to focus on improving providers, such as the [abandoned OpenFaaS provider](https://github.com/pulumi/pulumi-openfaas).
- Less complexity. Less language runtimes to install.

Take this for a grain of salt. You guys are making amazing software and changing how we approach configuration. I am just a little concerned about this making other components suffer. But perhaps you have some very large clients that demand higher-level libraries for every programming language available. Though that could become a very slippery slope.

**Comment by CyrusNajmabadi** [comment]
Thanks for the feedback @brandonkal !

**Comment by pavel-v-chernykh** [comment]
Consider wasm as a target platform. So that cross language libraries might be easier to get https://hacks.mozilla.org/2019/08/webassembly-interface-types/

**Comment by lukehoban** [comment]
> The goal of the prototype is to instantiate a `@pulumi/eks` Cluster resource in a Python program. This involves creating a way for the Python language host to launch a NodeJS language host, load the `@pulumi/eks` library in the target language host, pass arguments to the Cluster constructor, and receive outputs from the created Cluster object. The goal is explicitly not to create a general-purpose remote object protocol.

A prototype that accomplishes the above is now available in https://github.com/pulumi/pulumi/pull/3711.

**Comment by ringods** [comment]
> Consider wasm as a target platform. So that cross language libraries might be easier to get

I like this thought experiment. If all the supported languages compile into WebAssembly (WASM), the interoperability is handled on this layer.

Running the compiled code could be done with this VM:
https://github.com/WAVM/WAVM

**Comment by Place1** [comment]
I'd be very keen to try and apply this to my work at https://github.com/place1/kloudlib

**Comment by leezen** [comment]
Providing an update on where we are with this effort. First, some housekeeping, I removed the P1 label simply because we use those labels to track urgent issues for things like panics, bugs, etc. This is still one of the top priorities for the team.

Second, We have the code in place for Python and .NET for the pulumi-eks package. Go is close and should be ready in the next few days. The work remaining is as follows:

- Fix the getResource bug (https://github.com/pulumi/pulumi/issues/5940)
- Fix the bug around the marshalling of the ID (https://github.com/pulumi/pulumi/issues/5939)

While trying to get things ready last week, we ran into some bugs in the engine and we want to improve our coverage there. To that end, we will also close out https://github.com/pulumi/pulumi/issues/5943 before releasing the EKS in Python and .NET and making it available.

After those are complete, we expect to be able to cut a release of pulumi-eks that will allow you to use that package in Python, .NET, and Go.

**Comment by infin8x** [comment]
#### Status week of February 1, 2021: 🟢 

- This work is making good progress. We hope to have an internally-reviewable version of the guide to author a multi-language component available sometime in this milestone.

**Comment by leezen** [comment]
We now have examples of authoring your own multi-language components available as template repositories:

* https://github.com/pulumi/pulumi-component-provider-ts-boilerplate
* https://github.com/pulumi/pulumi-component-provider-go-boilerplate

Subsequently, we'll be closing out this issue as the core technology pieces are there for users to write multi-language components. We're now focusing on improving the authorship experience to reduce the necessary boilerplate and make it easier to write components. You can track these issues via the `area/multi-language-components` issues label in this repository. We'd also love to hear your feedback on writing multi-language components -- please file issues related to your experience or find us on slack.pulumi.com to let us know how we can help.
