### ISSUE TITLE
Tracking issue for all changes that would require a version bump

### ISSUE THREAD

**Issue by CyrusNajmabadi** [pulumi/pulumi#2611]
This is the tracking issue for all changes that would be a breaking change in `@pulumi/pulumi` and would require a version bump.

Right now this is:

- [ ] `features/componentOpt`: https://github.com/pulumi/pulumi/pull/2609
- [ ] `features/all`: https://github.com/pulumi/pulumi/pull/2527
- [ ] Removing ComponentResource's constructor's 'props' parameter: https://github.com/pulumi/pulumi/issues/2635

**Comment by lukehoban** [comment]
We merged all of the above so closing this out.
