### ISSUE TITLE
Complete Support for .NET

### ISSUE THREAD

**Issue by lukehoban** [pulumi/pulumi#3470]
.NET is broadly supported in preview as of Pulumi 1.5 :tada:

This issue tracks remaining work to complete the support for .NET.

Done:
- [x] Provide API to merge two instances of `InputMap<T>` (PR https://github.com/pulumi/pulumi/pull/3485)
- [x] Can we add an indexer to output lists? (`cosmosAccount.ConnectionStrings[0]`) PR https://github.com/pulumi/pulumi/pull/3481
- [x] Add a more descriptive error message if somebody tries to run a Pulumi program with `dotnet run`. Now it complains about missing `PULUMI_MONITOR` env var. (PR https://github.com/pulumi/pulumi/pull/3479)
- [x] Enable "nullable" support in our resource packages. (PRs https://github.com/pulumi/pulumi-terraform-bridge/pull/69 https://github.com/pulumi/pulumi-terraform/pull/514)
- [x] Aliases (PR #3420)
- [x] Mixins: SAS tokens for storage (PR https://github.com/pulumi/pulumi-azure/pull/408).
- [x] Add .NET Examples to tests (https://github.com/pulumi/examples/pull/475)
- [x] Add Kubernetes codegen support (pulumi/pulumi-kubernetes#863)
- [x] Add icons to provider NuGet packages (PR https://github.com/pulumi/pulumi-terraform-bridge/pull/84 https://github.com/pulumi/pulumi-terraform/pull/513)
- [x] `StackReference` (PR #3511)
- [x] Docker provider (`docker.Image` PR https://github.com/pulumi/pulumi-docker/pull/115 examples https://github.com/pulumi/examples/pull/482)
- [x] Make it easy to log an exception. https://github.com/pulumi/pulumi/pull/3399#discussion_r338797447 PR https://github.com/pulumi/pulumi/pull/3602

In progress:
- [ ] Add .NET tests to provider repos
- [ ] Set the csproj file name to the project name when created from a template (CLI change done, templates to be changed)

Need review:
- [ ] Apply improved namespace naming to all other providers (except AWS, Azure, AzureAD).

Tracked in separate issues:
- [ ] PowerShell support #3473 #3507
- [ ] Clean things up between `Stack` and `ComponentResource` #3619
- [ ] API .NET reference docs https://github.com/pulumi/docs/issues/2137
- [ ] Add Windows test coverage for some subset of .NET examples https://github.com/pulumi/examples/issues/497
- [ ] Add the work for TerraformRemoteState in pulumi-terraform https://github.com/pulumi/pulumi-terraform/issues/516
- [ ] Mixins: `ArchiveFunctionApp` https://github.com/pulumi/pulumi-azure/issues/433
- [ ] Testing Pulumi .NET programs - example, blog, any required support in the library #3633
- [ ] Use MEF and switch to a plugin model instead of an exe model.  This would allow dep-injection to be used by clients and would lead to a more natural way of exposing the user's 'Stack' with attributes instead of with them having a `Main` method which bounces in and back from `Pulumi`. #3499
- [ ] Enable running `pulumi up` on precompiled binaries in case people want to split the compilation from execution #3509
- [ ] Attach a debugger to the .NET program #1372
- [ ] Get rid of Serilog dependency, use MS logging extensions #3636
- [ ] Add support for the new language to `tf2pulumi` https://github.com/pulumi/tf2pulumi/issues/140
- [ ] Dynamic Providers #3638
- [ ] Investigate 'lifting' on .net outputs like we do with JS outputs: #3639
- [ ] Callback serialization #3640
- [ ] Should we allow arbitrary objects to be exported from a stack?  We could convert them to POCOs and export those (like we do with js/ts/python).  #3641
- [ ] First class unknowns: #3642
- [ ] what is our SxS story #3643
- [ ] F#-idiomatic API #3644

Parked:
- [ ] namespaces for all the parts of a package resource.  i.e. we have Pulumi.Aws, Pulumi.Aws.S3, pulumi.Aws.S3.Inputs, etc.  Do we need/want all of these?  Is it an acceptable usre experience (both for intellisense and docs)?  etc. etc.
- [ ] Should our invokes allow async-inputs, or only sync-values?  ts specifies only snyc values.  js-impl allows async values.  etc. etc.
- [ ] https://github.com/pulumi/pulumi/pull/3399#discussion_r338766787.  Can we get off of using static state.  Perhaps have the instance state computed and passed into the RunAsync method as an appropriate context.  Note: inputs/outputs are difficult here as they look at state like IsPreview and don't always have a clear way to determine that value.
- [ ] Commit `version.txt` to git with some sensible version in it to make it easy to compile and run .NET SDKs without running any other tasks from make. (contributor experience)

**Comment by mikhailshilkov** [comment]
I'm closing this umbrella issue. We'll track the remaining tasks in separate issues in corresponding repos - see the description for some pointers.
