### ISSUE TITLE
Plan for fully removing dependency on deasync and entirely removing this avenue for hangs/crashes.

### ISSUE THREAD

**Issue by CyrusNajmabadi** [pulumi/pulumi#3528]
Here's the current plan - original details below for historical context.

Phase 1 (Q4'19):
- [x] Remove use of synchronous invokes in [awsx](https://github.com/pulumi/pulumi-awsx/pull/470) (potentially a breaking change for some AWSX APIs)
- [x] Remove use of synchronous invokes in [eks](https://github.com/pulumi/pulumi-eks/pull/292)
- [x] Remove use of synchronous invokes in [all examples](https://github.com/pulumi/examples/pull/502)
- [ ] Remove use of synchronous invokes in [`tf2pulumi` generated code](https://github.com/pulumi/tf2pulumi/issues/144) (including all docs)

Phase 2 (H1'20):
- [ ] Make [all invokes async-only in the engine](https://github.com/pulumi/pulumi/issues/3693) (breaking change for every `.getFoo` method in TypeScript/JavaScript) as part of Pulumi 2.0.

----

Note: requires breaking changes in Pulumi APIs and will require updates to user programs.

First, the list of work necessary is as follows:

- [ ] remove deasync dependency from @pulumi/pulumi. https://github.com/pulumi/pulumi/pull/3598
- [ ] remove synchronous `invoke` codepath. https://github.com/pulumi/pulumi/pull/3598
- [ ] async Component construction. https://github.com/pulumi/pulumi/issues/3646
- [ ] remove synchronous StackReference.getOutputSync (add in async version that gives the value). https://github.com/pulumi/pulumi/pull/3598
- [ ] Update generator and resource SDKs to not expose sync invokes. https://github.com/pulumi/pulumi-terraform-bridge/pull/88. https://github.com/pulumi/pulumi-aws/pull/812
- [ ] update awsx (and other component libraries) to be async (for any codepath that constructs resources). https://github.com/pulumi/pulumi-awsx/pull/454
- [ ] provide simple way for a Pulumi app to be entirely async (i.e. async-main). https://github.com/pulumi/pulumi/pull/3321
- [ ] update all examples to use this model.
- [ ] update all docs to explain and demonstrate this model.

Justifications for the above work:

Currently, it is still possible for users to run into hangs/crashes due to deasync doing normal development using Pulumi. This can happen when a user uses a ProviderResource (like aws.Provider) and either:

1. directly calls into a synchronous data-source
2. uses a library like awsx which then indirectly calls a synchronous data-source for them.

This issue is one that users can work around, but not in a pleasant manner.  First, the normal development model we recommend can lead to them hitting this instead of avoiding it.  Second, the workaround for the issue (calling `await ProviderResource.register`) is both undiscoverable and often unpleasant to contort the code into.  This workaround is definitely necessary to have to give people a way to cheaply deal with the issue, but is not a healthy place for our platform and sdks for the medium and long term.

A longer term solution is necessary where this problem no longer exists.  Fundamentally, due to the need to actually support async providers (very important for k8s scenarios), our hands are forced, and we must bubble up asynchrony through our platform and then through components built on top of that.  To that end, a full solution to this issue looks like the following:

1. Entirely remove deasync from the @pulumi/pulumi SDK.  This means
1.1. No more synchronous data-source 'invoke' (very impactful).  (async invokes will exist).
1.2. No more 'StackReference-getOutputSync' *on a stack reference*.   (there will be a way to get the values asynchronously).
2. Removing synchronous data-sources means that all data-source will be promise-returning and will impact all resource sdks.
3. Many/Most/All APIs in our component libraries will need to become async.
3.1 Even if a component api does not need any data-sources, it may end up needing that in the future, warranting a breaking change if we don't start with it being async.  
3.2 This likely means constructors for component resources are not directly exposed.  Instead, async
factory methods will be needed to ensre that components can asynchronously get the information they need for async-data-sources and then perform their necessary flow-control off of them.

Fundamentally, this is just pushing an async model through data-sources/components.  Because of the viral nature of async, it is likely this will push the user to need to be async throughout their program. While JS/Node are inching toward a future where that is fully supported and pleasant, they will likely not get there for some time.  It will also only be pleasant for those on the bleeding edge of Node.  Because of this, we should likely also include https://github.com/pulumi/pulumi/pull/3321 in our work.  This PR makes it possible for a user to export a top level async function as the start of their Pulumi program.  i.e.:

```ts
// main.ts
import * as pulumi from "@pulumi/pulumi";
import * as awsx from "@pulumi/awsx";

export = async () => {
   const vpc = await awsx.ec2.Vpc.create(...);
   const cluster = awsx.ecs.Cluster.create(...);

   return { vpcId: vpc.id, ... };
}
```

While not as attractively simple as just a plain synchronous JS/TS app, this is very low friction for the user.  Specifically, practically any existing Pulumi program can transition to this with mostly mechanical effort.  

This entire effort will fundamentally break/deprecate existing code that performs synchronous data-source calls or uses our synchronous components.  It will need to come with a major semver update.  Along with that, we will need to update our docs/examples accordingly.

**Comment by CyrusNajmabadi** [comment]
Tagging @lukehoban @pgavlin

**Comment by pgavlin** [comment]
> No more 'StackReference-getOutputSync' on an async stack reference. This is less impactful.

Can you elaborate on this?

**Comment by CyrusNajmabadi** [comment]
>Can you elaborate on this?

yes: https://github.com/pulumi/pulumi/blob/a600d1652666a1eff4e7284546f029f1db05480e/sdk/nodejs/stackReference.ts#L164-L179

if the stack-reference *name* is itself an async-input, then we are forced to use deasync.  I hope we can simply deprecate this functionality and require that the name of a StackReference must be non-async.

Does that help?

**Comment by pgavlin** [comment]
> Does that help? Do you see any serious concerns around deprecatin the ability to pass in async-names to StackReference?

The thing that worries me is the inconsistency. I would have imagined that rather than deprecate the ability to pass in the name as an `Input<string>`, we would deprecate `getOuptutSync` et. al. and instead provide async replacements.

**Comment by CyrusNajmabadi** [comment]
>The thing that worries me is the inconsistency. I would have imagined that rather than deprecate the ability to pass in the name as an Input<string>, we would deprecate getOuptutSync et. al. and instead provide async replacements.

Yes, that sounds reasonable.  I will update the plan and i can start this on monday.

**Comment by lukehoban** [comment]
We landed https://github.com/pulumi/pulumi-awsx/pull/470 which was one of the biggest pieces of this work.  Given progress, closing this out - and will track remaining work in the issues linked above.
