### ISSUE TITLE
Pulumi 2.0 roadmap

### ISSUE THREAD

**Issue by joeduffy** [pulumi/pulumi#3591]
This is a tracking issue for the Pulumi 2.0 roadmap. It will be updated as the roadmap shapes up. Please let us know what you think with appropriate emojis and comments. Thank you! 💜 

Pulumi 2.0 is the next major version of Pulumi. Being a major release, minor breaking changes are possible, however we are striving to avoid that wherever possible. Many of the features of Pulumi 2.0 are being actively developed in "preview" as part of Pulumi 1.x builds, and are targeting general availability as part of Pulumi 2.0. You can continue to work with these new features as part of Pulumi 1.x builds over the coming weeks and months as we finalize the features of Pulumi 2.0.

Here are some of the larger features that are expected to be part of Pulumi 2.0:

- Languages
    - [x] GA of Go support (https://github.com/pulumi/pulumi/issues/1614)
    - [x] GA of .NET support (https://github.com/pulumi/pulumi/issues/3470)
- [x] GA of "CrossGuard" policy as code (https://github.com/pulumi/pulumi-policy/labels/pac%2Fga)
- [x] Testing (https://github.com/pulumi/pulumi/issues/2287)
- [x] GA of self-host / on-premises (https://www.pulumi.com/docs/guides/self-hosted/)
- [x] Resource-based API docs (https://github.com/pulumi/docs/issues/2264)

We will continue to invest in many smaller issues, including bug fixes, incremental improvements, and new capabilities around existing features, both as part of Pulumi 1.x and included in Pulumi 2.0.

You can share your feedback on areas you'd like to see more investment by commenting here, [opening a new issue](https://github.com/pulumi/pulumi/issues/new), or [upvoting an existing issue](https://github.com/issues?q=org%3Apulumi+sort%3Areactions-%2B1-desc+is%3Aopen). Community and customer feedback is what drives everything we do at Pulumi, so your feedback is essential to us ensuring a great 2.0 release!

You can also track the milestone roadmap more granularly as it evolves in the [Pulumi Roadmap](https://github.com/pulumi/pulumi/wiki/Roadmap).

**Comment by trondhindenes** [comment]
One thing that I find super-disappointing is that SSO is only available at the enterprise level. I don't understand why Pulumi (and many SaaS apps) treat single-sign on as something only the largest organizations want/need. (btw kudos to Datadog and Opsgenie for including sso support in all tiers)

We're only around 40 developers, but we have a policy of only using sso-integrated services (with a few exceptions, but very few), which is a contributing reason we've skipped on Pulumi so far.

Please consider either including sso/saml support on all pricing tiers, or at least offer it as a paid add-on so that it can be activated on all tiers. It would allow us to at least test out Pulumi in a few projects.

**Comment by LouisAmon** [comment]
For me a critical feature would be to be able to develop my own providers in any language.
Dynamic Providers are nice but they aren't a stable solution. I haven't been able to find any example of e.g. a Python provider.

I'm willing to put money on it and hire people to develop open-source providers for 3rd parties (e.g. Stripe, Snowflake, etc.) without going through Terraform and its terrible Golang & custom DSL.

Regardless, good job to the Pulumi team so far, you're doing great 👍

**Comment by ctolkien** [comment]
Will add my voice to the chorus of SSO. We're much smaller than the 40 person team at @trondhindenes , however SSO would be greatly appreciated.

**Comment by swoop-alex** [comment]
Looking forward to 
Cross-language libraries (#2430) as an enabler for 

JVM Languages support (Java, Kotlin, Scala, Groovy, Clojure etc) https://github.com/pulumi/pulumi/issues/1539

**Comment by swoop-alex** [comment]
also looking forward to

- High level libraries (like awsx) for Azure and GCP

- Native Pulumi providers for AWS/Azure/GCP

**Comment by rarous** [comment]
It would be really nice to have #1691 in 2.0 roudmap

**Comment by Place1** [comment]
It's good to see #2287 in the roadmap. I'd be really keen for it to also address #2506. My use-case is to bake pulumi into a broader internal CLI tool as well as have some more control over the process running pulumi; i.e. have my own nodejs program (`node ./my-program.js`) execute the pulumi up.

**Comment by Place1** [comment]
If I can throw another one into the mix 😬 #2209 would be a real enabler. I think it can greatly simplify multi-stack deployments and perhaps allow for typescript module imports for resource outputs in other stacks.

**Comment by valdecircarvalho** [comment]
Support for Oracle Cloud (OCI) is a must. 
OCI is getting traction more and more in the Enterprise market. 
Pulumi should support it!

**Comment by Pavel910** [comment]
#2506 is the key feature for us, as we need to integrate Pulumi with our existing CLI tooling.

Great job so far!! 🚀

**Comment by lukehoban** [comment]
We've delivered all of the features tracked here in the `2.0` betas, and are gearing up to release `2.0.0` GA very soon!  Closing this tracking issue out. :tada:

For everyone who left feedback on additional areas they wanted to see - thank you! 🙌   Many of those did end up being done as part of 2.0, and the others we're looking at for 2.x releases over the coming months.  Definitely encourage giving :+1: on the primary tracking issues for things that are priorities for you or your team - we do carefully track the top upvoted issues across all the Pulumi projects to inform investments in ongoing development.
