### ISSUE TITLE
Introduce Pulumi resource model schema and unified code generators

### ISSUE THREAD

**Issue by lukehoban** [pulumi/pulumi#3764]
Today we have multiple code generators - one for `tfgen`, one for our Kubernetes provider, and several providers that have had to be hand written in every language because they do not fit either of the above.

Logically, these are all the same, and are tightly constrained by the need to represent the Pulumi resource model in the target language.

We plan to introduce a common intermediate schema that can be shared across all of these domains, such that we can use one shared set of code generators for all resource providers.

This will be used to replace existing code generators, to make it easier to build future providers, and as the foundation for significantly improved resource provider documentation.

Q2:
- [x] Define core schema model (https://github.com/pulumi/pulumi/pull/3749)
- [x] Add code generation for TypeScript (https://github.com/pulumi/pulumi/pull/3749)
- [x] Add code generation for Python(https://github.com/pulumi/pulumi/pull/3749)
- [x] Add code generation for .NET (https://github.com/pulumi/pulumi/pull/3749)
- [x] Add code generation for Go (https://github.com/pulumi/pulumi/pull/3749)
- [x] Replace `tfgen` for Go with usage of this shared code generator 
- [x] Replace `tfgen` for Python with usage of this shared code generator (https://github.com/pulumi/pulumi-terraform-bridge/pull/108)
- [x] Replace `tfgen` for Node.js with usage of this shared code generator (https://github.com/pulumi/pulumi-terraform-bridge/issues/179)
- [x] Replace `tfgen` for .NET with usage of this shared code generator 
- [x] Replace Kubernetes code generation for Go with usage of this shared code generator (https://github.com/pulumi/pulumi-kubernetes/pull/1029)
- [x] Replace Kubernetes code generation for Python with usage of this shared code generator (https://github.com/pulumi/pulumi-kubernetes/issues/1085)
- [x] Replace Kubernetes code generation for Node.js with usage of this shared code generator (https://github.com/pulumi/pulumi-kubernetes/issues/1053)
- [x] Replace Kubernetes code generation for .NET with usage of this shared code generator (https://github.com/pulumi/pulumi-kubernetes/issues/1084)
- [x] Generate resource-based documentation with language-agnostic docs derived from this schematization

Q3:
- [ ] Expand schema model to support component resources (and description of packages like `awsx` and `eks`) (https://github.com/pulumi/pulumi/issues/4784)

**Comment by lukehoban** [comment]
We've made good progress here where we must to deliver customer value.  The remaining work is to improve our internal engineering processes to truly unify on a single code generator.  I'm going to assume for now we'll commit to finishing that post 2.0, and opportunistically make progress where it helps us move faster prior to then.

**Comment by pgavlin** [comment]
This is complete.
