### ISSUE TITLE
Improve Python tooling experience for complex input/output shapes

### ISSUE THREAD

**Issue by lukehoban** [pulumi/pulumi#3771]
~We should strongly consider emitting TypedDicts for all dictionaries we use for inputs and outputs: https://www.python.org/dev/peps/pep-0589/.~

~This would provide some chance of decent tooling experiences for complex input/output shapes which are prevalent in Kubernetes.~

~We should do the same in `tfgen` as well, though the issue is incrementally less critical there.~

We decided to generate classes rather than use TypedDicts.

Remaining tasks

- [x] [#4789](https://github.com/pulumi/pulumi/issues/4789): Support serializing/deserializing Python classes
- [x] [#5140](https://github.com/pulumi/pulumi/issues/5140): Follow-up: Instantiate output types for calls to invoke
- [x] [#5141](https://github.com/pulumi/pulumi/issues/5141): Follow-up: Automatically generate `__init__` for input classes
- [x] [#5142](https://github.com/pulumi/pulumi/issues/5142): Follow-up: Support docstrings in IDE hover tooltips over output properties for resources and function results
- [x] Pulumi SDK release that contains [#4789](https://github.com/pulumi/pulumi/issues/4789) (Pulumi 2.9.0)
- [x] [#4790](https://github.com/pulumi/pulumi/issues/4790): Python codegen: Emit classes for nested inputs/outputs
- [x] [In-Progress] Provider releases
- [x] [#4791](https://github.com/pulumi/pulumi/issues/4791): Python docgen: Refer to classes for nested inputs/outputs
- [x] [#4792](https://github.com/pulumi/pulumi/issues/4792): Python program codegen: Use classes when generating Python programs
- [ ] [In-Progress] [docs/#3534](https://github.com/pulumi/docs/issues/3534): Update Python docs to use classes for nested inputs/outputs
- [ ] [In-Progress] [examples/#700](https://github.com/pulumi/examples/issues/700): Update Python examples to use classes
- [x] [Done; Blocked on K8s provider release] [templates/#120](https://github.com/pulumi/templates/issues/120): Update Python templates to use classes
- [x] [Available] Demos
- [x] Blog post with screenshots/gifs and/or video

**Comment by justinvp** [comment]
If we wanted to avoid bumping the min required version of Python to 3.8, we could consider using dataclasses (requires 3.7): https://docs.python.org/3/library/dataclasses.html. Or just generate the equivalent code. As part of this, we should loosen up any code specifically looking for `dict` to look for container-like types instead and have the dataclasses emulate dictionaries (https://docs.python.org/3/reference/datamodel.html#emulating-container-types).

**Comment by praneetloke** [comment]
This is also relevant for resource docs generator. See this [comment](https://github.com/pulumi/docs/pull/2641#discussion_r393284316) as an example.

**Comment by leezen** [comment]
I've renamed the issue to reflect what we're really trying to do. The discussion from #4510 resulted in going forward with using dataclasses.

**Comment by justinvp** [comment]
Providers have been rolled out with these changes. There is some trailing docs and examples updates that are in-progress, tracked at https://github.com/pulumi/docs/issues/3534 and https://github.com/pulumi/examples/issues/700.
