### ISSUE TITLE
Add enum support to the schema and code generators

### ISSUE THREAD

**Issue by praneetloke** [pulumi/pulumi#4003]
This issue tracks enum support in the schema, codegen, sdk and docs.

* [x] Support enums in the pulumi schema.
* [x] [codegen/nodejs] Add typescript support for enums. #5433
* [x] [codegen/nodejs] Translate enum output properties. #5598 
* [x] [sdk/nodejs] Add support for enums.  #5600
* [x] [codegen/dotnet] Add C# support for enums. #5434
* [x] [sdk/dotnet] Add support for enums. #5601
* [x] [codegen/python] Add python support for enums. #5435
* [x] [sdk/python] Add support for enums. #5602
* [x] [codegen/go] Add go support for enums. #5436
* [x] [sdk/go] Add support for enums. #5603
* [x] Add enums to the docs. #5437
* [x] Schematize aws enum overlays. https://github.com/pulumi/pulumi-aws/issues/1130

**Comment by praneetloke** [comment]
I removed the size label and reassigned it to @tasiah. We will have a size estimate before this work begins.

**Comment by praneetloke** [comment]
@pgavlin I have split out the work to add support for typed-JSON objects in the schema. I am assigning this specific work item related to adding support for enums, to you.

**Comment by mikhailshilkov** [comment]
Azure API definitions have two types of enums:

- A "strong" enum with a fixed set of possible values, e.g. `LogLevel` with values of `Off, Verbose, Information, Warning, Error`
- A more relaxed enum that still has a list of possible values but instructs the clients to model this value as a `string`. This relaxes some restrictions about what constitutes a breaking change and adds flexibility. In practice, the actual values that end users would pass would still be from the enumerated set in most cases

We may want to have this distinction of closed/open enums in the schema and codegen too.

**Comment by komalali** [comment]
@mikhailshilkov can you explain a bit more about what you mean by "relaxed enum"? Or maybe an example from the Azure API?

Specifically, I'm trying to understand this:
> This relaxes some restrictions about what constitutes a breaking change and adds flexibility.

**Comment by mikhailshilkov** [comment]
@komalali See Azure docs here: http://azure.github.io/autorest/extensions/#x-ms-enum

They have a `modelAsString` property which instructs the client SDKs to give the type `string` to these fields instead of a proper enum. If the service defines possible values `A` and `B` for such a field, the SDK should still accept `C` as a value and send it to the service without a validation failure.

I imagine we could model "strict" enums as `type Strict = "A" | "B"` and "relaxed" as `type Relaxed = "A" | "B" | string`, or model it as a string and have some consts as `Relaxed.A = "A"; Relaxed.B = "B";`

**Comment by komalali** [comment]
Thinking of how to represent this in the `schema.json`.

Consider the strict enum:
```json
"strictEnumType": {
	"type": "string",
	"description": "Description of strictEnumType.",
	"enum": ["option-1", "option-2", "option-3"]
}
```

The relaxed enum is less clear. 
We could use a sentinel value (`"*"`) to represent "all other strings":
```json
"relaxedEnumType": {
	"type": "string",
	"description": "Description of relaxedEnumType.",
	"enum": ["relaxed-1", "relaxed-2", "relaxed-3", "*"]
}
```

Or represent the options using the "example" keyword:
```json
"relaxedEnumType": {
	"type": "string",
	"description": "Description of relaxedEnumType.",
	"example": ["relaxed-1", "relaxed-2", "relaxed-3"]
}
```

Thoughts @mikhailshilkov ?

**Comment by lukehoban** [comment]
I expect we would use `oneOf` to create a union type which we use elsewhere. In general - we’ve followed OpenAPI v3 fairly closely - unless there is a good reason to if encourage us to stick with their design model - it also supports well-defined language codegen baselines for us to adopt unless there is again a good reason not to. 

https://swagger.io/docs/specification/data-models/enums/

**Comment by lukehoban** [comment]
Ahh - though I see that maybe isn’t a perfect fit for this specific use case. 

I’d be interested in what the open api codegen default is for enums. And how APIs handle this genrally in OpenAPI.  I suppose azure had to add custom OpenAPI metadata and code generation logic to handle these two cases?  But is that the norm?

**Comment by komalali** [comment]
@lukehoban yeah here's the Azure docs for this: http://azure.github.io/autorest/extensions/#x-ms-enum

I'm not sure how to answer "Is that the norm?" I think no, since allowing any value defeats the purpose of an enum. But I'm very new to this area so any advice/direction is appreciated! Like, how do I find out "what the open api codegen default is for enums"?

**Comment by leezen** [comment]
It looks like it does what I'd expect, which is create a static class to hold the possible values while keeping the field a `string` https://github.com/Azure/autorest/pull/393

**Comment by mikhailshilkov** [comment]
Indeed, we can use Azure autorest implementations for inspiration. Here are some "enums" in [Go](https://github.com/Azure/azure-sdk-for-go/blob/4f14e3d53fba12172734d383af647730d06412d2/services/iothub/mgmt/2020-03-01/devices/models.go#L189) and its [source spec](https://github.com/Azure/azure-rest-api-specs/blob/97db8d1015c2780c2704fe0f55537ff1f4740140/specification/iothub/resource-manager/Microsoft.Devices/stable/2020-03-01/iothub.json#L2371)

**Comment by mikhailshilkov** [comment]
@komalali Also note that Microsoft provides a name for the enum type, so we should try to preserve it in the schema

**Comment by komalali** [comment]
@mikhailshilkov they also provide the possibility of having additional metadata like names and descriptions for each of the values http://azure.github.io/autorest/extensions/#x-ms-enum:~:text=values%3A,%2D%20value%3A%20Premium_LRS

They're not used in the spec yet as far as I can tell, but I imagine we would want to preserve that option as well? In which case, do we just absorb the metadata object altogether? "x-pul-enum"?

**Comment by mikhailshilkov** [comment]
@komalali Preserving the whole "extension" as-is sounds reasonable to me. It doesn't look like Open API has a standard alternative.
