### ISSUE TITLE
Improve stability and functionality of self-managed state backends

### ISSUE THREAD

**Issue by leezen** [pulumi/pulumi#4605]
This epic tracks overall improvements to non-Pulumi Console [backends](https://www.pulumi.com/docs/intro/concepts/state/) to make them more reliable and feature-complete.

- [ ] #2055 Fix code duplication between httpstate and filestate backends
- [x] #2522 Project name in stack identity inconsistent between backends
- [ ] #2801 Failed to load checkpoint after write failure to S3 backend
- [x] #2814 Using S3 backend with multiple projects is unpleasant
- [ ] #2996 Feature request: persist the filestate backend URL in Pulumi.<stackname>.yaml
- [x] #3194 Specifying an incorrect API service backend for pulumi login results in a confusing error message
- [x] #3395 StackReference doesn't support multiple backends
- [ ] #3683 Be able to move/transfer a stack from a backend to another
- [ ] #3714 [bug] s3 backend deletes state early and then tries to JSON parse html
- [ ] #3760 Add test coverage for all supported filestate backends
- [x] #3120 Simple project support for local backends
- [ ] #2058 Feature: Store release history in Kubernetes using CRDs
- [ ] #4665 Support configuration for pluggable backends and secrets providers
- [ ] #4679 S3 state provider will remove stack data on connection lost while `pulumi up`
- [ ] #5036 Concurrent Stack Updates Results in Reference Error with s3 Backend
- [ ] https://github.com/pulumi/pulumi-az-pipelines-task/issues/47 Read backend config from Pulumi.yaml
- [ ] #6074 Pulumi eats bandwidth (when using S3 backend)
- [ ] #8571 Don't touch local in stack rm
- [x] #9031 Use Pulumi.yaml template as schema to validate Pulumi.$stack.yaml

**Comment by ig0rsky** [comment]
@leezen so what's the proposed way of moving forward here? Is there draft somewhere that is being worked on for us to read?

**Comment by leezen** [comment]
There's a planned item to write a proposal tracked in https://github.com/pulumi/pulumi/issues/4710

**Comment by joeduffy** [comment]
@leezen @stack72 I see that https://github.com/pulumi/pulumi/issues/4710 was closed, but I couldn't find where we posted the design document for community feedback/visibility. Did we do that somewhere?

**Comment by stack72** [comment]
@joeduffy apologies for not posting this - this is the proposal we are going with

# Backend Enhancement Design Proposal

## Goal
Improve the experience of using the open source backends in Pulumi. This includes how back ends are configured

## Background
The Pulumi backends currently use the go-cloud library for interaction with AWS, Azure and GCP. The support for other clouds is lacking, therefore, it’s more difficult for Pulumi to support anything other than those 3 clouds. The configuration of these backends is also at the mercy of the go-cloud library as it uses Environment Variables for configuration. The existing backend implementation has also made it more difficult for users to use different backends per stack as they need to use `pulumi login / logout` on a stack or project change.

## Implementation

The configuration of our backends doesn’t have a wonderful user experience when it comes to changing between backends. Currently, if the user has a project that is set up with multiple stacks, and each stack has its own credentials for a backend, then the user would need to `pulumi logout`, set new environment variables and then `pulumi login` with these new variables. 

A better user experience, would be to codify the configuration of the backends in the Pulumi.<stack>.yaml file.e.g.:

```
config:
  aws:accessKey: <key for resource creation>
  aws:region: us-east-1
  aws:secretKey:
    secure: <secure key for resource creation>
  backend:
    s3:
      aws:accessKey: <key for s3 bucket access only>
      aws:region: store state in a difference bucket
      aws:secretKey:
        secure: <secure key for s3 bucket access>
```

This allows the user to be much more explicit and not need to pulumi login and pulumi logout between stacks that have separate configuration. 

Please note: we can *still* support the ability to login and logout of the SaaS if we so desire that configuration but we can also store that backend configuration in the yaml file as well, e.g.:

```
config:
  aws:accessKey: <key for resource creation>
  aws:region: us-east-1
  aws:secretKey:
    secure: <secure key for resource creation>
  backend:
    pulumiSaaS:
      pulumi:apiKey: <saas user token>
```

Or for local state storage it would look as follows:

```
config:
  aws:accessKey: <key for resource creation>
  aws:region: us-east-1
  aws:secretKey:
    secure: <secure key for resource creation>
  backend:
    local:
      path: $HOME/state/x
```

Please note, the backends names are by no means formal in these examples, this is just to show a **potential** configuration

**Comment by haneef95** [comment]
I believe that locking can be achieved with a git backend.
**Benefits:**
1. save having to deal with a different storage type for the project
2. Version control the state
3. Locking capability would be available too

I see that there are multiple options for Backends, however git isn’t one of them.

I believe git can be used as a backend for the state, project and stack files, in the below steps:

1. Use a dedicated git repo
2. Commit the files in a specified directory and branch.
3. Only fetch the required files, rather than the whole repo, as this repo could be used to store multiple stacks on different directories/branches.
4. For locking and unlocking:
- Method 1 (git LFS): use ‘git lfs lock’
- Method 2 (git - where lfs isn’t possible): Use another file suffixed with .lock, which should contain the lock state and time. Even a simple create/delete of the file should do.

Is there any plan for Pulumi to release git as a backend?

Thanks

**Comment by ringods** [comment]
I like the idea from @haneef95. If you consider this, here is a Go library for handling a lot of Git interactions: https://github.com/fluxcd/go-git-providers

**Comment by haneef95** [comment]
@stack72 thanks for the detailed input here.

In this case, I believe that the secrets in the yaml file will be encrypted.
Where will the encryption key be stored?


**Alternatively**
Can we opt to store the backend secret in one of the Available Encryption Providers (like Azure Key Vault)?

**Comment by jaxxstorm** [comment]
https://github.com/pulumi/pulumi/issues/5585

**Comment by stanislav-zaprudskiy** [comment]
To give some more insight on how slow (#6888) and hungry (#6074) the S3 backend is (read as: cumbersome to use), take a look on the output below:

```console
# pulumi stack export | du -sh
17M     .
# systemd-run -p IPAccounting=yes --wait $(for e in $(printenv | grep -E '(OS|PULUMI|AWS)_'); do echo --setenv=${e}; done | sort | tr '\n' ' ') pulumi up -f -y --non-interactive -C $PWD
Running as unit: run-u20.service
Finished with result: success
Main processes terminated with: code=exited/status=0
Service runtime: 2min 45.712s
IP traffic received: 90.8M
IP traffic sent: 140.3M
```

That was an update which did not update any resources. 
```
Resources:
    78 unchanged
```

While the initial deployment from scratch takes closer to an hour.

In the project there is nothing extra-ordinary: some network resources, Kubernetes cluster, 2 Helm charts (with CRDs), few extra-objects in Kubernetes. As the backend OpenStack's Swift is used (via S3 interface). When switching the project to local file backend, the updates are matter of minutes (from scratch) and seconds (when there is nothing to update):
```console
Service runtime: 28.193s
IP traffic received: 20.5M
IP traffic sent: 19.5M
```

**Comment by atrauzzi** [comment]
Dropping a reference to this ticket here: https://github.com/pulumi/pulumi/issues/8402

I think #2522 covers a good chunk of it, but there's also some frustrating behaviour of the `pulumi` CLI when dealing with state and configurations that ought ot be visited as part of this "quality of life" epic.

**Comment by asychev** [comment]
It looks there is almost zero progress after 2.5 years. Would be really great to know how many persons or organization NOT adopting Pulumi  just because of the issues above. Please, add reactions, let see how many of us.

**Comment by benlongo** [comment]
Since Pulumi has financial interest in preserving the poor performance and ergonomics of any alternative backends to their paid service, I don't think we should expect to see meaningful developments on these fronts. Unfortunately it appears community attempts to improve the situation via PRs have been largely ignored. The movement of this issue from Planned to Opportunity further indicates lack of interest.

**Comment by asychev** [comment]
@joeduffy Maybe we can get a minute of your attention here? Would be great to have clarity about the topic. Unfortunately the big ignorance keeps many people in strange state, can we just honestly and openly tell the truth? Some very good past comments from users magically disappear here, would be also great to know this is not because of any sort of _moderation_. Thanks!

**Comment by tomdavidson** [comment]
it does seem fair for pulumi to prioritize there resources elsewhere, but there does seem to be more than just a resource constraint.

I'm interested in making an open source API compatible backend that would not need the client to change, but with terraform's cdk I'm wondering if pulumi is worth the additional effort.

**Comment by asychev** [comment]
OK, it seems we've got very clear and transparent _answer_ here. Very sad, but very predictable.

**Comment by joeduffy** [comment]
Hi folks, I'm sorry for the radio silence here, it's definitely not intentional. I did want to reply with a few thoughts.

First, just a quick reply to this:

> Unfortunately the big ignorance keeps many people in strange state, can we just honestly and openly tell the truth? Some very good past comments from users magically disappear here, would be also great to know this is not because of any sort of moderation.

I looked into this specific "disappearing" comments, and the only instances I saw -- including the one a few days before this reply -- were deleted by the authors themselves. There is no moderation going on here, and one of our internal company values is "Share Openly and Be Honest," which we strive to do with our community too. To the extent we've been too quiet on this thread, it's not from a desire to mislead or be deceptive, it's honestly just our own struggles to keep up with things.

On that note, a broader reply:

This area is very important to us. Community is, always has been, and always will be, everything to us. It's a mistake that we ended up in this situation in the first place. When we initially added projects support to the backends, we just didn't do that correctly in the filestate backend. We've at least learned from this and strive not to add any more debt going forward.

For the specific issue of project support, [we did make a run at this right around the time this came up](https://github.com/pulumi/pulumi/pull/9262), but we had to revert it due to unforeseen design issues. This points to one of the challenges--the desire to keep filestate and httpstate backends consistent--but we will get better at this. Since then the team has been hard at work figuring out the right design and I heard today they came to agreement so we will have a fix soon. @justinvp, can we share that design openly, and link to it here?

One thing that makes this tough for is is that 2/3rds of our community uses the httpstate backend with our service, as well as 99% of our customers. That's usually because collaboration, security, reliability, and performance are just really good out of the box without "DIY" work. That's not to say the 1/3rds who do not aren't important to us--again, community is everything--but we're still a relatively small team and it does cause difficulties when looking at and prioritizing this specific work.

I tried to write down some of our philosophy to help folks internally prioritize.

In summary, we strive to always do what's in the best interest of the community. Of course, that includes both httpstate backend users, as well as filestate ones. That means, we are committed to

* Actively fixing known pain points, including correctness and performance issues
* Actively improving the usability of the filestate backend anywhere it falls short in comparison to httpstate
* Being proactive with architecture so as not to build up tech debt in any one backend (sadly we violated this rule with the project system which has led to the specific pain under discussion)

We've actually been doing "ok" at these, even if it's not very obvious. We need to do a better job announcing and blogging exciting new features in this area, since we have historically just shipped them quietly. For instance, we've added concurrency support once S3 supported the new consistency models ~2 years ago, and every significant Pulumi feature including, for example, Policy as Code, is supported by the filestate backend, which were conscious choices to ensure filestate remains as great an experience as we can offer to folks. I do understand the list of known issues above is not small, and I'd like to see many more checkmarks in the list above, but the progress also hasn't been zero.

The mega-issue here actually does cloud things a little for us, because it's a mix of big and small things. Please do upvote the individual issues as we look at those regularly when prioritizing, and we'd love to hear more about what -- beyond the filestate project issues which will be soon behind us -- are important things holding back your own adoption of Pulumi.

Really appreciate the patience; our community has grown fast, and our team not nearly as fast, and we're doing our best to keep up. Believe me, I personally read every reply here and we will strive to do better with transparency and responsiveness.

**Comment by justinvp** [comment]
If shared our plan for enabling support for project-scoped stacks in the filestate backend at https://github.com/pulumi/pulumi/issues/2522#issuecomment-1426496284

**Comment by asychev** [comment]
@joeduffy Your clean and transparent answer is much appreciated, thanks for that.

> That's not to say the 1/3rds who do not aren't important to us--again, community is everything--but we're still a relatively small team and it does cause difficulties when looking at and prioritizing this specific work.

For some companies usage of Pulumi Service might be simply not acceptable scenario for many reasons. Also for those who simply want to try Pulumi for the first time without investing money straight away before real evaluation - the fundamental features basically pay walled (you hit cross stack references issues [like this one](https://github.com/pulumi/pulumi/issues/2522) quickly in any real project). And I do believe this might have impact on Pulumi adoption rate quite a lot.

 I'm looking forward to see what will be the next steps here.

**Comment by james-blitzm** [comment]
> That's usually because collaboration, security, reliability, and performance are just really good out of the box without "DIY" work.

I hear where you are coming from, but not sure that security fits here. Many organisations will simply not be able to accept sharing of detailed information about their infrastructure with a third-party. I expect that will be a showstopper for many potential customers/users.

**Comment by joeduffy** [comment]
Totally understand this, and am 100% very sensitive to the security and compliance concerns. I would guess this is actually the biggest reason many folks start on the filestate backends first even those who eventually move over to httpstate.

I do want to point out one subtle thing with Pulumi that's easy to overlook: _our service doesn't need, use, or store your cloud credentials_. I say this because it's different than many other products out there (like Terraform Cloud AFAIK, which does actually have your credentials on the server). We have a unique client/server architecture where all credentials are on the client, which you control (in your own data center, CI/CD server, wherever you run the Pulumi CLI) and they stay there. This is detailed a bit in our [security whitepaper](https://www.pulumi.com/security/pulumi-cloud-security-whitepaper.pdf) and I'll admit, we've been through a ton of security reviews with Global 2k companies where their security team was fully on board with our SaaS backend thanks to this architecture choice.

That said, we do store "infrastructure metadata," so not saying this is _never_ a concern. Just that if the credentials thing is why folks were worried, they need not worry, although again it's not-so-obvious. For other kinds of secrets, we do have built-in secrets management, and [there are many configuration options](https://www.pulumi.com/docs/intro/concepts/secrets/#configuring-secrets-encryption) that ensure only clients with keys that you control can encrypt them, such that nobody here at Pulumi, nor a hypothetical attacker, could even decrypt secrets if they got their hands on them. This is fairly bulletproof and trusted by many Global 2ks -- I mention because this, plus the architectural choices above, eliminate the majority of concerns, but none of it's entirely obvious.

Still 100% committed to filestate and being sensitive to the concerns, just wanted to clarify some subtleties :-)

**Comment by pecigonzalo** [comment]
> One thing that makes this tough for is is that 2/3rds of our community uses the httpstate backend with our service

Maybe those are the only ones that survived and adopted Pulumi, as a result this ratio is biased. I think having issues like [this](https://github.com/pulumi/pulumi/issues/6074) about S3 performance (and similar GCS ones) is a showstopper for many when trying to check "should I used Pulumi, or stick to Terraform".

I know for myself that is the case. Deploying some Chart with Pulumi for example, the stack takes ~10Mb and becomes so slow and eats so much bandwidth that its not really something Im sure I want to commit to.

Are there any other httpstate backends than Pulumi Cloud? If there were, maybe this would not be as much of a problem. I think it's misleading to even calling it the "httpstate backend" when it's not a general http based backend.

**Comment by tomdavidson** [comment]
@pecigonzalo wait, what? Your saying there is something inherent with other backend options making them too slow and there is something special about Pulumi Cloud's service that makes not too slow? We all know these other backends preform must fine with other software, so the problem is the Pulumi implementation (just as #6074 suggests).

Your comment read as yes, the self-managed sate backend implementations suck but that's ok, and there is nothing to improve because the self-managed state backend implementations suck.

**Comment by pecigonzalo** [comment]
> @pecigonzalo wait, what? Your saying there is something inherent with other backend options making them too slow and there is something special about Pulumi Cloud's service that makes not too slow? We all know these other backends preform must fine with other software, so the problem is the Pulumi implementation (just as #6074 suggests).
> 
> 
> 
> Your comment read as yes, the self-managed sate backend implementations suck but that's ok, and there is nothing to improve because the self-managed state backend implementations suck.

I think you are misreading it. On the contrary, I'm saying that Pulumi is almost unusable without the Cloud backend, and that reading "2/3rd of the community is happy" is quite possibly survivor bias, as the rest of the users simply left. Particularly for something being called "the http state backend" which is non existent outside of the cloud service.

**Comment by tomdavidson** [comment]
Yeah I definitely misread. Sorry about that. 

I understand the point now I think it's pretty good one.

**Comment by asychev** [comment]
Another year passed and it seems there is no near `100% committed to filestate` as was promised by @joeduffy.
https://github.com/pulumi/pulumi/issues/4605 not moving, issues like https://github.com/pulumi/pulumi/issues/6074 still there, but there is a time for something like https://github.com/pulumi/pulumi/pull/15268...
Anybody surprised?

**Comment by Frassle** [comment]
> https://github.com/pulumi/pulumi/issues/4605 not moving, issues like https://github.com/pulumi/pulumi/issues/6074 still there, but there is a time for something like https://github.com/pulumi/pulumi/pull/15268...

To be fair, #15268 was all of a few minutes work to rename some fields. 
There is some internal movement on #6074, unfortunately about the only thing we can do here is a robustness vs performance tradeoff. We're limited by what's possible when your protocol is "just files". 
And there has been some improvements to the list of issues in #4605, we just haven't been that great at tracking it all back to these old issues.

We are 100% committed to filestate but we are a very small team, there's been parts of this year with basically only one engineer working on the pulumi engine at a time.

**Comment by chicagobuss** [comment]
Any movement here, folks?  Been another 7 months...

**Comment by yann-soubeyrand** [comment]
> There is some internal movement on [#6074](https://github.com/pulumi/pulumi/issues/6074), unfortunately about the only thing we can do here is a robustness vs performance tradeoff. We're limited by what's possible when your protocol is "just files".

I tend to agree with this statement and, if people are willing to drop a bit of robustness to gain some performance, setting both `PULUMI_EXPERIMENTAL` and `PULUMI_SKIP_CHECKPOINTS` environment variables to `true` brought speed improvements in our case.

However, wouldn’t it be possible to push in the file state only the incremental diffs and only compute the whole state at the end of the Pulumi operation (maybe it already works like that, but I was under the impression that Pulumi pushed the whole state after each transactional change during an operation)?

**Comment by davidfries** [comment]
Howdy folks, I'm sure myself and many others would love to see some movement this year on [ #6074](https://github.com/pulumi/pulumi/issues/6074)

**Comment by jaxxstorm** [comment]
Have any of the folks eagerly watching this thread considered engaging with Pulumi via a support contract or via $ investment into the product to get movement on this?

**Comment by Sodki** [comment]
> Have any of the folks eagerly watching this thread considered engaging with Pulumi via a support contract or via $ investment into the product to get movement on this?

Yes. My previous company spent around $100k with Pulumi, but of course we don't set the product roadmap. That's not how it works.
