### ISSUE TITLE
[Epic] Automation API: C#

### ISSUE THREAD

**Issue by EvanBoyle** [pulumi/pulumi#5596]
The current plan is to pick the work back up on November 16th with the goal of delivering it (along with [Python](https://github.com/pulumi/pulumi/issues/5299)) by the end of the year. We've scoped the effort and it looks like the following:

- [ ] Create `Workspace` Interface [TypeScript reference](https://github.com/pulumi/pulumi/blob/master/sdk/nodejs/x/automation/workspace.ts). Note there are some places where the [Go interface](https://github.com/pulumi/pulumi/blob/master/sdk/go/x/auto/workspace.go) is more complete (cancel, export, import). Ideally, we should shoot for the same level of completeness as the Go impl. 
- [ ] Implement `RunPulumiCmd` [TypeScript reference](https://github.com/pulumi/pulumi/blob/master/sdk/nodejs/x/automation/cmd.ts)
- [ ] `LocalWorkspace` Implementation [TypeScript reference](https://github.com/pulumi/pulumi/blob/master/sdk/nodejs/x/automation/localWorkspace.ts)
- [ ] `Stack` implementation supporting local programs [TypeScript reference](https://github.com/pulumi/pulumi/blob/master/sdk/nodejs/x/automation/stack.ts)
- [ ] Implement idiomatic structured error handling [TypeScript reference](https://github.com/pulumi/pulumi/blob/master/sdk/nodejs/x/automation/errors.ts)
- [ ] Add `InlineProgram` support. This involves creating a C# implementation of the gRPC LanguageServer. TypeScript references: [LanguageServer](https://github.com/pulumi/pulumi/blob/master/sdk/nodejs/x/automation/server.ts), [Preview consumption](https://github.com/pulumi/pulumi/blob/master/sdk/nodejs/x/automation/stack.ts#L228-L250), and [Up consumption](https://github.com/pulumi/pulumi/blob/master/sdk/nodejs/x/automation/stack.ts#L147-L169)
- [ ] Add `RemoteProgram` support (clone and setup programs from git). Go references: [LocalWorkspace](https://github.com/pulumi/pulumi/blob/master/sdk/go/x/auto/local_workspace.go#L514-L521), and [checkout impl](https://github.com/pulumi/pulumi/blob/master/sdk/go/x/auto/git.go), note that this is not yet implemented in TypeScript. 

There are also many tests that should be replicated. These should make the implementation and acceptance criteria fairly straight forward:

https://github.com/pulumi/pulumi/blob/master/sdk/nodejs/tests/automation/localWorkspace.spec.ts
https://github.com/pulumi/pulumi/blob/master/sdk/go/x/auto/local_workspace_test.go
https://github.com/pulumi/pulumi/blob/master/sdk/go/x/auto/errors_test.go

One special thing to note here is that C# programs offer two modes of execution, one via a `Stack` class, and one via a plain function. We need to support both styles of program when we design `InlineProgram` support so as to minimize (or eliminate) any changes that C# users would have to make to their existing `Stack` classes. There is also a naming conflict here as `Stack` is a class name we use in Automation API, but it already exists in the C# SDK. One option here is to create another implementation of [`Deployment`](https://github.com/pulumi/pulumi/blob/master/sdk/dotnet/Pulumi/Deployment/Deployment.cs) that is used for `InlinePrograms` that has the `Up` `Preview` etc functions exposed. You should only ever be using one form of deployment in a program, either `Deployment.runAsync` or `Deployment.Up` so this would probably work out fine. 

We have started a branch, but there is only the first commit that sets up the package and has the beginnings of the `Workspace` interface definition: https://github.com/pulumi/pulumi/compare/auto/dotnet

This is actually a great opportunity for contributors to get involved and accelerate the process. The work is well-scoped and there are reference implementations. The work listed above is in order of operation. We're highly motivated to make sure this work lands soon, so this is a unique opportunity to contribute. We could offer support to anyone in the community who's interested in participating in the following forms:

1. Give you the context that you need. We'll do a kickoff via Zoom where we do an architecture overview, analyze key components of the system, and talk about what the implementation in C#  will look like. 
2. Access to the engineering team via slack.
3. Regular time with me debugging and talking through problems on Zoom. 
4. Prompt code reviews
5. T-shirts and swag

If anyone is interested in contributing please reach out in a comment, DM me on community slack, or email me at "first at pulumi dot com".

**Comment by dferretti** [comment]
@EvanBoyle  I've got kind of a weird ask for you. What do you think about adding the Slack integration to this repository?

I know I can subscribe to this issue for updates, but it would be cool to also get updates on each commit with something like
`/github subscribe pulumi/pulumi commits:auto/dotnet`

I didn't think it would work for a repository I'm not owner of, but I did just find this issue https://github.com/integrations/slack/issues/454 which makes me believe it could work. 

It does ask for some "write" permissions though so I understand not wanting to add it:
![image](https://user-images.githubusercontent.com/24608502/96605372-22b35480-12c4-11eb-91aa-b9938b70b9ae.png)

**Comment by dferretti** [comment]
Actually, that might not be necessary - I just realized you can get Atom feeds for branches, and Slack can subscribe to those as well. 

https://github.com/pulumi/pulumi/commits/auto/dotnet.atom
https://slack.com/help/articles/218688467-Add-RSS-feeds-to-Slack

Forget I said anything!

**Comment by mikhailshilkov** [comment]
@EvanBoyle Do you know what still needs to be done for GA? Could you update the list in this issue?

**Comment by orionstudt** [comment]
I can refresh that #5761 did everything except:

- `RemoteProgram` support
- Stack `import/export/cancel` support
- Concurrency (#6139)

Also during #5761 we talked about re-naming the following methods:

1. `GetConfig` -> `GetConfigValue`
2. `GetAllConfig` -> `GetConfig`
3. `SetConfig` -> `SetConfigValue`
4. `SetAllConfig` -> `SetConfig`

And we haven't reflected those changes in the other SDKs yet.

**Comment by mikhailshilkov** [comment]
Thank you @orionstudt 

@infin8x @leezen  Do you want to keep this issue open and add a current list of GA TODO items, or should we close and track elsewhere?

**Comment by leezen** [comment]
I'll rename the title for this to be specifically about having C# ready (I need to review @orionstudt's examples and blog posts -- thanks for contributing them!). I'll separately track the items @orionstudt mentioned above in the general tracking issue (which is in a private repo as it includes launch-related details).

Once we have the blog and examples out, I'll close this issue.

**Comment by infin8x** [comment]
The [blog post](https://www.pulumi.com/blog/automation-api-dotnet/) and [examples](https://github.com/pulumi/automation-api-examples/tree/main/dotnet) for the C# Automation API are now available. A huge thanks goes to @orionstudt for contributing this crucial piece of functionality!

We're excited for you to try out the automation API from C#. Let us know how it goes [on Twitter](https://twitter.com/PulumiCorp) or in our [Community Slack](https://slack.pulumi.com/).
