### ISSUE TITLE
[Epic] Pulumi 4.0 Changes Tracking

### ISSUE THREAD

**Issue by leezen** [pulumi/pulumi#7346]
_Updated November 2, 2021 by `@infin8x`_

We periodically release new major versions of Pulumi, with a combination of new features and important breaking changes. This epic is a living document tracking those features and breaking changes that we think will make it into the release.

### New features

- [ ] #2247
- [x] #2318 

### Quality-of-life improvements

- [ ] pulumi/pulumi-terraform-bridge#315 (for import and new languages)
- [ ] Update to latest version of Terraform provider plugin
- [x] pulumi/pulumi-kubernetes#1788
- [ ] Update runtimes for mixins (e.g. Node 14 in `pulumi-aws`)
- [x] https://github.com/pulumi/pulumi/issues/9704
- [ ] https://github.com/pulumi/pulumi/issues/4261
- [ ] https://github.com/pulumi/pulumi/issues/10261

### Deprecations

- [x] Remove `pulumi query`? (currently experimental and unmaintained)
- [ ] Remove dynamic providers? No path to supporting them in all language but we now have path to native providers in most languages.

### Improvements for component authors

- [ ] #2484
- [ ] pulumi/home#1649 (needs more clarity/investigation)
  - [ ] #8299
- [ ] #5941 
- [ ] Make passing inputs to the engine consistent across SDKs

### Small improvements/enhancements

- [ ] #8371 (.NET SDK)
- [ ] https://github.com/pulumi/pulumi/issues/8946

### Cut

-  ~https://github.com/pulumi/pulumi/issues/9143~
- ~#2307?~
- ~#7435~

**Comment by viveklak** [comment]
Consider culling EOLed api versions in providers, e.g: https://github.com/pulumi/pulumi-kubernetes/issues/1638

**Comment by joeduffy** [comment]
We should consider refreshing by default in 4.0: https://github.com/pulumi/pulumi/issues/2247

**Comment by viveklak** [comment]
Adding https://github.com/pulumi/pulumi/issues/7346

**Comment by beddari** [comment]
Cutting #2307 is pretty sad, this comment is on point and I hope you reconsider https://github.com/pulumi/pulumi/issues/2307#issuecomment-756540859

**Comment by qdzlug** [comment]
Would very much like to see #2307 as part of 4.0, implementing this functionality would be extremely helpful for our workflow.

**Comment by bruvik** [comment]
Another vote for #2307 in 4.0

**Comment by leezen** [comment]
We need to also examine if it makes sense to try to do #7012 as part of 4.0.

**Comment by iwahbe** [comment]
We should add https://github.com/pulumi/pulumi/issues/8523 as part of 4.0.

**Comment by stack72** [comment]
I believe we should handle https://github.com/pulumi/pulumi/issues/6384 as part of the 4.0 release - this is a breaking change as it's moves some common code around. This would break the deployment dependency between pkg and sdk

**Comment by joeduffy** [comment]
For consideration in 4.0: https://github.com/pulumi/pulumi/issues/7376#issuecomment-981980774

**Comment by Frassle** [comment]
We should remove the empty constructor for InputTuple in the dotnet sdk (https://github.com/pulumi/pulumi/pull/8733/files#r783327551)

**Comment by Frassle** [comment]
We'll want to add sequence numbers back to dynamic providers: https://github.com/pulumi/pulumi/pull/8849

**Comment by iwahbe** [comment]
Replace `blang/semver` with `hashicorp/go-version` or similar. See https://github.com/pulumi/pulumi/pull/8920#issuecomment-1030025736 for details.

**Comment by iwahbe** [comment]
Revisit how `pulumi config set` works with regards to type recognition. We should unify behavior between top level and pathed stacks. See 
- https://github.com/pulumi/pulumi/issues/8575
- https://github.com/pulumi/pulumi/issues/8401
- https://github.com/pulumi/pulumi/issues/4295
- https://github.com/pulumi/pulumi/issues/5442
for motivation.

**Comment by iwahbe** [comment]
Improve TS compilation: 
- https://github.com/pulumi/pulumi/pull/9049
- https://github.com/pulumi/pulumi/pull/8199

**Comment by ringods** [comment]
Could you consider #9007 for 4.0? Releasing thirdparty providers via Github Releases would be a welcome addition for [Pulumiverse](https://github.com/pulumiverse).

**Comment by dixler** [comment]
It was [mentioned](https://github.com/pulumi/pulumi/pull/8199) that this issue may be considered in pulumi 4.0 since it will likely require existing projects to have to modify their `package.json`
- https://github.com/pulumi/pulumi/issues/8177 

PR
- https://github.com/pulumi/pulumi/pull/10122

**Comment by iwahbe** [comment]
In reference to #11327, we should change python ResourceOptions.merge to not overload a static and dynamic method. Python doesn't support it, and the abstraction is leaky.

**Comment by RobbieMcKinstry** [comment]
Offering up https://github.com/pulumi/pulumi/issues/2603  -- heavy lifting required, but something we could do non-breaking, opt-in during v3 -- support both formats simultaneously.

**Comment by gunzy83** [comment]
> Remove dynamic providers? No path to supporting them in all language but we now have path to native providers in most languages.

I just implemented my first one of these a few weeks ago for a simple use case to work around an issue in AWS. I had a couple more use cases in mind which were essentially orchestration glue (ordering, delays, checks) where I needed that glue inside the resource model (kinda like Cloudformation CustomResources). Is there some documentation somewhere for where the path forward might lie?

**Comment by jre21** [comment]
I would very much like to see #12432 in 4.0, both because it would be a big quality-of-life improvement on its own, and because #2247 would make for a very poor experience with the current UX.

**Comment by dixler** [comment]
I saw this in passing and thought it would make sense to comment it on this issue

https://github.com/pulumi/pulumi/blob/1260aafd50a9fcb834d379101ec62edb964a936f/pkg/resource/deploy/source_eval.go#L1319-L1328
