### ISSUE TITLE
Deeper fix of Go SDK to be compatible with changes in #7059

### ISSUE THREAD

**Issue by emiliza** [pulumi/pulumi#7434]
Based on @pgavlin's investigation from https://github.com/pulumi/pulumi/issues/7359 (with relation to the changes in #7059)

### M61/62
- [x] https://github.com/pulumi/pulumi/issues/7846 (Merged)
PR: https://github.com/pulumi/pulumi/pull/7861
- [x] https://github.com/pulumi/pulumi/issues/7847 (Merged)
PR: https://github.com/pulumi/pulumi/pull/7861
- [x] https://github.com/pulumi/pulumi/issues/7845 (Merged)
PR: https://github.com/pulumi/pulumi/pull/7870
- [x] https://github.com/pulumi/pulumi/issues/7848 (Merged) 
PR: https://github.com/pulumi/pulumi/pull/7928
PR: https://github.com/pulumi/pulumi/pull/7975
- [x] https://github.com/pulumi/pulumi/issues/7849 (Merged)
PR: https://github.com/pulumi/pulumi/pull/7958
- [x] Aiming for dev build to validate above ~9/15 (pushed from 9/1)
- [x] https://github.com/pulumi/pulumi/issues/7850 (Merged)
PR: https://github.com/pulumi/pulumi/pull/7925
- [x] https://github.com/pulumi/pulumi/issues/7851 (Merged)
PR: https://github.com/pulumi/pulumi/pull/7926
- [x] https://github.com/pulumi/pulumi/issues/8007 (Merged)

### M63
- [x] https://github.com/pulumi/pulumi/pull/7959
- [x] https://github.com/pulumi/pulumi/issues/8165
- [x] https://github.com/pulumi/pulumi/issues/8166
- [x] https://github.com/pulumi/pulumi/issues/8189

### M64
- [x] https://github.com/pulumi/pulumi/issues/8006
- [x] https://github.com/pulumi/pulumi/issues/8155
- [x] https://github.com/pulumi/pulumi/issues/8156

### Defer for TBD
-  .NET SDK unmarshaling (used in MLC provider)

**Comment by t0yv0** [comment]
What does it mean for an output value to be marshaled? Does marshaling always await the output value until it resolves to a concrete value and set of dependencies and then passes that over the boundary? E.g. in Haskell notation this is what we're actually passing?

```
data ResolvedOutput a = Unknown | Output IsSecret a [Dependency]
```

If that is all we do it should be a good simplification. If found RPC code that already awaits inputs as part of doing RPC, transforming them to resolved values. Preserving types when passing resolved Outputs would simplify that.

If we plan on passing unresolved outputs and especially resolving unresolved outputs across the RPC boundary I'd love a little more elaboration  on the semantics.

**Comment by t0yv0** [comment]
Resolved it's the former (fully await any time crossing the rpc boundary). Thanks!

**Comment by justinvp** [comment]
I'm curious how the expanded `resource.Output` will interact with `resource.Secret`.

I haven't looked closely, but it looks like it may be possible to have a secret that contains an unknown value:

https://github.com/pulumi/pulumi/blob/4f914bfea83135cd90d715143ba91aff36a296a6/sdk/go/common/resource/properties.go#L382-L384

As well as an unknown that contains a secret value:

https://github.com/pulumi/pulumi/blob/4f914bfea83135cd90d715143ba91aff36a296a6/sdk/go/common/resource/properties.go#L392-L395

What will the structure of a property value that's a secret look like using the `resource` types? And what will the RPC structure look like?
