### ISSUE TITLE
Epic: Improving external contributor experience

### ISSUE THREAD

**Issue by AaronFriel** [pulumi/pulumi#8780]
## Issues/stories:

1. As an external contributor, assuming dependencies in `CONTRIBUTING.md` are installed, running `make` should succeed on a clean clone of the repo.
2. As an external contributor, running `make` should not create resources in a my Pulumi account or on cloud providers without explicit opt-in.
3. As a maintainer, external contributions using a fork and pull request workflow should be testable via comment-commands.

## 1. Errors on running `make`

Make can fail on different platforms & userlands for a wide variety of reasons, but as a MVP we should succeed on *nix 

- [sdk/dotnet] Dotnet LocalPulumiCmdTests test fails locally, runs in CI
- https://github.com/pulumi/pulumi/pull/8773
- https://github.com/pulumi/pulumi/pull/8774

### Issues in other repos on running `make`

- https://github.com/pulumi/pulumi-aws-native/pull/322
- https://github.com/pulumi/pulumi-google-native/pull/302

## 2. Cloud resources deployed during test

In CI, we have access to a Pulumi Service org `pulumi-test`, and tests default the env var `PULUMI_TEST_ORG` to that value and will deploy stacks in that org. For external contributors, we want running tests that deploy real resources to be opt-in, and for `make` to not perform those steps by default.

- [ ] `pulumi whoami` in CI environment resolves to `pulumi-test` OR we define `PULUMI_TEST_ORG` in all CI jobs
- [ ] Add a separate `make cloud-test` target for tests that create resources, dependency of tests initially
- [ ] Update CI jobs to run the new make target explicitly and remove dependency on `cloud-test`
- [ ] Modify the makefile to default to the result of `pulumi whoami`, something like: `PULUMI_TEST_ORG=$(PULUMI_TEST_ORG:-$(pulumi whoami))`

## 3. Evergreen main branch with external contributions

Fork-PR workflows don't trigger tests on the upstream branch that have access to secrets, for good reason! However, when a maintainer wants to run a complete suite of tests against an incoming PR, we should be able to do so. Once we've implemented the tasks in separating out cloud resource deployments in [pulumi/pulumi](https://github.com/pulumi/pulumi), we may want to follow the same process in other repos as well.

- [meta] Ensure `pulumi/` repos allow maintainers to run tests against fork PRs on command.
- [meta] Separate out safe-to-run unit tests from cloud resource/secret consuming tests
- Debug why `pulumi-azuread` tests did not run on this PR after `/run-acceptance-tests` command: https://github.com/pulumi/pulumi-azuread/actions/runs/1714331026
- Verify that a command exists & works to run tests in [pulumi/pulumi-aws-native](https://github.com/pulumi/pulumi-aws-native)

**Comment by jkodroff** [comment]
`make dep` or `make ensure` is a common convention installing dependencies, but I imagine it would be very difficult to make such a target platform-independent.

**Comment by AaronFriel** [comment]
@jkodroff for sure. I think CONTRIBUTING.md requiring minimum versions for Go, Node, .NET, Python and any non-trivial tooling makes sense, and then using language-specific cross-platform tooling as much as possible: e.g.: yarn/npm to install TypeScript, `go install` to get golangci-lint would be nice, and so on.
