### ISSUE TITLE
Tracking Issue: Standardize `provider` and `providers` behaviour

### ISSUE THREAD

**Issue by iwahbe** [pulumi/pulumi#8796]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details
After an a design discussion ([internal link](https://docs.google.com/document/d/1Z0P-XU5AW-dhwKQCWHEiau_7kIAsF9j4CUFaPlMlGj4/edit#)), we have decided to implement the following:
1. `provider` indicates that a provider must be used. This takes priority over the ambient parent map or the providers map. `provider` is added to `providers` to be discoverable by children, but does not override an already existing provider for the same package. 
    a.  Do merge with warning if a conflict exists (between provider and providers). 
    b.  Warning should indicate that this merge will be depreciated in 6 months.
2.  `providers` indicates a set of providers that may be used, by both the resource and its children. We never promote a provider from `providers` to `provider`. 
3. Both `provider` and `providers` can be given. They operate independently as described above.
4. SDKs error if `provider` does not agree with the type of the resource being created. 
a. If python is passed a map of providers, warn if a key does not match its expected value (Provider.package). We warn instead of erroring to prevent breaking programs that have unused (and incorrect) provider maps. Warning should be converted to an error for the second release of July 2022. 
b. Depreciate accepting a Mapping for the python/go SDK. 

## TODO 
- [ ] Update each SDK
a. Update semantics in each SDK
b.  Update commends in docstrings across language SDKs to speak truth-y things
  - https://github.com/pulumi/pulumi/pull/8770
  - https://github.com/pulumi/pulumi/pull/8819
  - https://github.com/pulumi/pulumi/pull/8838
  - https://github.com/pulumi/pulumi/pull/8882
- [x] https://github.com/pulumi/pulumi-hugo/pull/997
- [ ] Consider updating developer docs with gory detail of how it plays out case by case
- [ ] If we’re inspired we can stand up a proposal for cleaning it up in a breaking way for 4.0 and add it to 4.0 wait list
a. Dropping all the maps and just having lists for “providers” is an obvious cleanup even if we don’t do anything else.
