### ISSUE TITLE
Support for partial creation/update in resource providers

### ISSUE THREAD

**Issue by lukehoban** [pulumi/pulumi#992]
Today, if a `Create` or `Update` operation in a provider returns an error, we assume that the operation did nothing.  In practice, that is frequently not true - the operation may have done part of the work to affect the create or update, but failed on a subsequent step.

This leads to leaked resources that are not tracked by Pulumi checkpoints.

We need to support providers returning partial success information along with errors from a `Create` or `Update`, so that we can record that a resource was created, even if did not fully complete being initialized.

Our providers based on `pulumi-terraform` have access to this information on partial success via TF [Partial State](https://www.terraform.io/guides/writing-custom-terraform-providers.html#error-handling-amp-partial-state).  Other providers will likely need the same capability.

See https://github.com/pulumi/pulumi-aws/issues/154 for a concrete example.

**Comment by hausdorff** [comment]
Since this is (IMO) pretty easily **the biggest known problem with the Pulumi Kubernetes provider,** and since it is definitely necessary to be fixed to complete our product-level objectives, I'd like to propose we move ahead with a fix for this in the next milestone. I'm happy to do it myself.

## The issue

Quick recap:

* It is extremely common for Kubernetes resources to be _created_ but fail to _initialize_ (_e.g._, a `Deployment` object was created but the containers don't have the env vars they need). In most cases they will retry forever.
* In this case, running `pulumi update` will fail, because the resource already exists. Also, it will poll until it times out, which is confusing to the user.

## Proposed solution _for the Kubernetes provider_

I sense that this is a complex issue for AWS, but for Kubernetes, I believe the solution to be relatively simple, because it seems like it should just call `Update` (rather than, say, calling `Delete` and then `Create`).

Distilling an offline conversation with @swgillespie:

* Engine needs to tell service something like “we created this thing, but initialization failed”. This could be implemented as a bool, `initFailure` in the return message of `Create` and `Update`, which is true iff resource creation succeeded and initialization failed.
* The service needs to persist that as part of the checkpoint. Subsequent calls to `pulumi update` should then result in a `Update` rather than a `Create`.
* The core logic of `Update` probably does not need to change, because whether we should delete-and-replace actually depends on which fields were changed, and `Update` already implements this behavior. For example, hard-replacing a `Deployment` will cause all sorts of bad things to happen, one of which is that the `NodePort` is re-allocated; this is not what we want, we should replace it only if specific fields are touched.

This implies a change to the checkpoint schema, and the gRPC interface, so I want to make sure we're on the same page that this is a good way to go.

Given the importance of landing this fix, I'm hoping to get sign off relatively soon. cc @swgillespie, @lukehoban, @pgavlin

**Comment by mmdriley** [comment]
for reference, my findings on Terraform `Partial` and `SetPartial`: https://github.com/pulumi/pulumi-aws/issues/179#issuecomment-377391505 and https://github.com/pulumi/pulumi-aws/issues/179#issuecomment-400080237

**Comment by hausdorff** [comment]
Status update:

- [x] Core engine changes to make partial updates possible. pulumi/pulumi #1590.
- [ ] Kubernetes implementation of partial update. **[in review]** [pulumi/pulumi-kubernetes #88](https://github.com/pulumi/pulumi-kubernetes/pull/88)

I also think we should _not_ close this issue until the following issues are resolved, which are the difference in making this practically useful:

- [ ] ctrl-c results properly results in partial update [pulumi/pulumi-kubernetes](https://github.com/pulumi/pulumi-kubernetes/issues/89)

**Comment by lukehoban** [comment]
@hausdorff I believe this is done now?  Note that we do have https://github.com/pulumi/pulumi-terraform/issues/213, but we can track that work separately.

**Comment by swgillespie** [comment]
Closing this in favor of https://github.com/pulumi/pulumi-terraform/issues/213. The engine can handle this now thanks to @hausdorff's work, so the next thing to do is to enlighten `tfbridge` to use it.
